# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .config_obj import *
from .provider import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_openziti.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_openziti.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "openziti",
  "mod": "index",
  "fqn": "pulumi_openziti",
  "classes": {
   "openziti:index:ConfigObj": "ConfigObj"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "openziti",
  "token": "pulumi:providers:openziti",
  "fqn": "pulumi_openziti",
  "class": "Provider"
 }
]
"""
)
