# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Callable, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs

__all__ = ['EdgeRouterPolicyArgs', 'EdgeRouterPolicy']

@pulumi.input_type
class EdgeRouterPolicyArgs:
    def __init__(__self__, *,
                 identity_roles: pulumi.Input[Sequence[pulumi.Input[str]]],
                 name: pulumi.Input[str],
                 semantic: pulumi.Input[str],
                 edge_router_roles: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, Any]]] = None):
        """
        The set of arguments for constructing a EdgeRouterPolicy resource.
        """
        EdgeRouterPolicyArgs._configure(
            lambda key, value: pulumi.set(__self__, key, value),
            identity_roles=identity_roles,
            name=name,
            semantic=semantic,
            edge_router_roles=edge_router_roles,
            tags=tags,
        )
    @staticmethod
    def _configure(
             _setter: Callable[[Any, Any], None],
             identity_roles: pulumi.Input[Sequence[pulumi.Input[str]]],
             name: pulumi.Input[str],
             semantic: pulumi.Input[str],
             edge_router_roles: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
             tags: Optional[pulumi.Input[Mapping[str, Any]]] = None,
             opts: Optional[pulumi.ResourceOptions]=None):
        _setter("identity_roles", identity_roles)
        _setter("name", name)
        _setter("semantic", semantic)
        if edge_router_roles is not None:
            _setter("edge_router_roles", edge_router_roles)
        if tags is not None:
            _setter("tags", tags)

    @property
    @pulumi.getter(name="identityRoles")
    def identity_roles(self) -> pulumi.Input[Sequence[pulumi.Input[str]]]:
        return pulumi.get(self, "identity_roles")

    @identity_roles.setter
    def identity_roles(self, value: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(self, "identity_roles", value)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def semantic(self) -> pulumi.Input[str]:
        return pulumi.get(self, "semantic")

    @semantic.setter
    def semantic(self, value: pulumi.Input[str]):
        pulumi.set(self, "semantic", value)

    @property
    @pulumi.getter(name="edgeRouterRoles")
    def edge_router_roles(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        return pulumi.get(self, "edge_router_roles")

    @edge_router_roles.setter
    def edge_router_roles(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "edge_router_roles", value)

    @property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, Any]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, Any]]]):
        pulumi.set(self, "tags", value)


class EdgeRouterPolicy(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 edge_router_roles: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 identity_roles: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 semantic: Optional[pulumi.Input[str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, Any]]] = None,
                 __props__=None):
        """
        Create a EdgeRouterPolicy resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: EdgeRouterPolicyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a EdgeRouterPolicy resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param EdgeRouterPolicyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(EdgeRouterPolicyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            kwargs = kwargs or {}
            def _setter(key, value):
                kwargs[key] = value
            EdgeRouterPolicyArgs._configure(_setter, **kwargs)
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 edge_router_roles: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 identity_roles: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 semantic: Optional[pulumi.Input[str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, Any]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = EdgeRouterPolicyArgs.__new__(EdgeRouterPolicyArgs)

            __props__.__dict__["edge_router_roles"] = edge_router_roles
            if identity_roles is None and not opts.urn:
                raise TypeError("Missing required property 'identity_roles'")
            __props__.__dict__["identity_roles"] = identity_roles
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if semantic is None and not opts.urn:
                raise TypeError("Missing required property 'semantic'")
            __props__.__dict__["semantic"] = semantic
            __props__.__dict__["tags"] = tags
            __props__.__dict__["_assimilated"] = None
            __props__.__dict__["_links"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["edge_router_roles_display"] = None
            __props__.__dict__["id"] = None
            __props__.__dict__["identity_roles_display"] = None
            __props__.__dict__["updated_at"] = None
        super(EdgeRouterPolicy, __self__).__init__(
            'openziti:index:EdgeRouterPolicy',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'EdgeRouterPolicy':
        """
        Get an existing EdgeRouterPolicy resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = EdgeRouterPolicyArgs.__new__(EdgeRouterPolicyArgs)

        __props__.__dict__["_assimilated"] = None
        __props__.__dict__["_links"] = None
        __props__.__dict__["created_at"] = None
        __props__.__dict__["edge_router_roles"] = None
        __props__.__dict__["edge_router_roles_display"] = None
        __props__.__dict__["id"] = None
        __props__.__dict__["identity_roles"] = None
        __props__.__dict__["identity_roles_display"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["semantic"] = None
        __props__.__dict__["tags"] = None
        __props__.__dict__["updated_at"] = None
        return EdgeRouterPolicy(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def _assimilated(self) -> pulumi.Output[bool]:
        return pulumi.get(self, "_assimilated")

    @property
    @pulumi.getter
    def _links(self) -> pulumi.Output[Mapping[str, 'outputs.Link']]:
        return pulumi.get(self, "_links")

    @property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[str]:
        return pulumi.get(self, "created_at")

    @property
    @pulumi.getter(name="edgeRouterRoles")
    def edge_router_roles(self) -> pulumi.Output[Sequence[str]]:
        return pulumi.get(self, "edge_router_roles")

    @property
    @pulumi.getter(name="edgeRouterRolesDisplay")
    def edge_router_roles_display(self) -> pulumi.Output[Sequence['outputs.NamedRole']]:
        return pulumi.get(self, "edge_router_roles_display")

    @property
    @pulumi.getter
    def id(self) -> pulumi.Output[str]:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="identityRoles")
    def identity_roles(self) -> pulumi.Output[Sequence[str]]:
        return pulumi.get(self, "identity_roles")

    @property
    @pulumi.getter(name="identityRolesDisplay")
    def identity_roles_display(self) -> pulumi.Output[Sequence['outputs.NamedRole']]:
        return pulumi.get(self, "identity_roles_display")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def semantic(self) -> pulumi.Output[str]:
        return pulumi.get(self, "semantic")

    @property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Mapping[str, Any]]]:
        return pulumi.get(self, "tags")

    @property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[str]:
        return pulumi.get(self, "updated_at")

