# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Callable, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['EnrolledIdentityArgs', 'EnrolledIdentity']

@pulumi.input_type
class EnrolledIdentityArgs:
    def __init__(__self__, *,
                 enrollment_jwt: pulumi.Input[str]):
        """
        The set of arguments for constructing a EnrolledIdentity resource.
        """
        EnrolledIdentityArgs._configure(
            lambda key, value: pulumi.set(__self__, key, value),
            enrollment_jwt=enrollment_jwt,
        )
    @staticmethod
    def _configure(
             _setter: Callable[[Any, Any], None],
             enrollment_jwt: pulumi.Input[str],
             opts: Optional[pulumi.ResourceOptions]=None):
        _setter("enrollment_jwt", enrollment_jwt)

    @property
    @pulumi.getter(name="enrollmentJwt")
    def enrollment_jwt(self) -> pulumi.Input[str]:
        return pulumi.get(self, "enrollment_jwt")

    @enrollment_jwt.setter
    def enrollment_jwt(self, value: pulumi.Input[str]):
        pulumi.set(self, "enrollment_jwt", value)


class EnrolledIdentity(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enrollment_jwt: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a EnrolledIdentity resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: EnrolledIdentityArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a EnrolledIdentity resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param EnrolledIdentityArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(EnrolledIdentityArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            kwargs = kwargs or {}
            def _setter(key, value):
                kwargs[key] = value
            EnrolledIdentityArgs._configure(_setter, **kwargs)
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enrollment_jwt: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = EnrolledIdentityArgs.__new__(EnrolledIdentityArgs)

            if enrollment_jwt is None and not opts.urn:
                raise TypeError("Missing required property 'enrollment_jwt'")
            __props__.__dict__["enrollment_jwt"] = None if enrollment_jwt is None else pulumi.Output.secret(enrollment_jwt)
            __props__.__dict__["identity_json"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["enrollmentJwt", "identityJson"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(EnrolledIdentity, __self__).__init__(
            'openziti:index:EnrolledIdentity',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'EnrolledIdentity':
        """
        Get an existing EnrolledIdentity resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = EnrolledIdentityArgs.__new__(EnrolledIdentityArgs)

        __props__.__dict__["enrollment_jwt"] = None
        __props__.__dict__["identity_json"] = None
        return EnrolledIdentity(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="enrollmentJwt")
    def enrollment_jwt(self) -> pulumi.Output[str]:
        return pulumi.get(self, "enrollment_jwt")

    @property
    @pulumi.getter(name="identityJson")
    def identity_json(self) -> pulumi.Output[str]:
        return pulumi.get(self, "identity_json")

