// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.openziti.rest_model.outputs;

import com.pulumi.core.annotations.CustomType;
import java.util.Objects;

@CustomType
public final class PostureQuery {
    private PostureQuery() {}

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PostureQuery defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        public Builder() {}
        public Builder(PostureQuery defaults) {
    	      Objects.requireNonNull(defaults);
        }

        public PostureQuery build() {
            final var _resultValue = new PostureQuery();
            return _resultValue;
        }
    }
}
