// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rest_model

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
	"internal"
)

var _ = internal.GetEnvOrDefault

type IdentityAuthenticators struct {
}

type IdentityAuthenticatorsOutput struct{ *pulumi.OutputState }

func (IdentityAuthenticatorsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*IdentityAuthenticators)(nil)).Elem()
}

func (o IdentityAuthenticatorsOutput) ToIdentityAuthenticatorsOutput() IdentityAuthenticatorsOutput {
	return o
}

func (o IdentityAuthenticatorsOutput) ToIdentityAuthenticatorsOutputWithContext(ctx context.Context) IdentityAuthenticatorsOutput {
	return o
}

func (o IdentityAuthenticatorsOutput) ToOutput(ctx context.Context) pulumix.Output[IdentityAuthenticators] {
	return pulumix.Output[IdentityAuthenticators]{
		OutputState: o.OutputState,
	}
}

func init() {
	pulumi.RegisterOutputType(IdentityAuthenticatorsOutput{})
}
