# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Callable, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('openziti')


class _ExportableConfig(types.ModuleType):
    @property
    def assimilate(self) -> Optional[bool]:
        """
        Assimilate an existing object during create
        """
        return __config__.get_bool('assimilate')

    @property
    def insecure(self) -> Optional[bool]:
        return __config__.get_bool('insecure')

    @property
    def password(self) -> Optional[str]:
        """
        The password. It is very secret.
        """
        return __config__.get('password')

    @property
    def uri(self) -> Optional[str]:
        """
        The URI to the API
        """
        return __config__.get('uri')

    @property
    def user(self) -> Optional[str]:
        """
        The username. It's important but not secret.
        """
        return __config__.get('user')

    @property
    def version(self) -> Optional[str]:
        return __config__.get('version')

