// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"internal"
)

var _ = internal.GetEnvOrDefault

// Assimilate an existing object during create
func GetAssimilate(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "openziti:assimilate")
}
func GetInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "openziti:insecure")
}

// The password. It is very secret.
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "openziti:password")
}

// The URI to the API
func GetUri(ctx *pulumi.Context) string {
	return config.Get(ctx, "openziti:uri")
}

// The username. It's important but not secret.
func GetUser(ctx *pulumi.Context) string {
	return config.Get(ctx, "openziti:user")
}
func GetVersion(ctx *pulumi.Context) string {
	return config.Get(ctx, "openziti:version")
}
