// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.openziti.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IdentityCreateEnrollmentArgs extends com.pulumi.resources.ResourceArgs {

    public static final IdentityCreateEnrollmentArgs Empty = new IdentityCreateEnrollmentArgs();

    @Import(name="ott")
    private @Nullable Output<Boolean> ott;

    public Optional<Output<Boolean>> ott() {
        return Optional.ofNullable(this.ott);
    }

    @Import(name="ottca")
    private @Nullable Output<String> ottca;

    public Optional<Output<String>> ottca() {
        return Optional.ofNullable(this.ottca);
    }

    @Import(name="updb")
    private @Nullable Output<String> updb;

    public Optional<Output<String>> updb() {
        return Optional.ofNullable(this.updb);
    }

    private IdentityCreateEnrollmentArgs() {}

    private IdentityCreateEnrollmentArgs(IdentityCreateEnrollmentArgs $) {
        this.ott = $.ott;
        this.ottca = $.ottca;
        this.updb = $.updb;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IdentityCreateEnrollmentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IdentityCreateEnrollmentArgs $;

        public Builder() {
            $ = new IdentityCreateEnrollmentArgs();
        }

        public Builder(IdentityCreateEnrollmentArgs defaults) {
            $ = new IdentityCreateEnrollmentArgs(Objects.requireNonNull(defaults));
        }

        public Builder ott(@Nullable Output<Boolean> ott) {
            $.ott = ott;
            return this;
        }

        public Builder ott(Boolean ott) {
            return ott(Output.of(ott));
        }

        public Builder ottca(@Nullable Output<String> ottca) {
            $.ottca = ottca;
            return this;
        }

        public Builder ottca(String ottca) {
            return ottca(Output.of(ottca));
        }

        public Builder updb(@Nullable Output<String> updb) {
            $.updb = updb;
            return this;
        }

        public Builder updb(String updb) {
            return updb(Output.of(updb));
        }

        public IdentityCreateEnrollmentArgs build() {
            return $;
        }
    }

}
