[project]
  name = "osmit_gmbh_openziti"
  description = "A Pulumi provider for managing Ceph Rados Gateway resources."
  dependencies = ["parver>=0.2.1", "pulumi>=3.231.0,<4.0.0", "semver>=2.8.1", "typing-extensions>=4.11,<5; python_version < \"3.11\""]
  readme = "README.md"
  requires-python = ">=3.9"
  version = "1.0.0a0+dev"
  [project.urls]
    Homepage = "https://github.com/OSMIT-GmbH/pulumi-openziti"
    Repository = "https://github.com/OSMIT-GmbH/pulumi-openziti"

[build-system]
  requires = ["setuptools>=61.0"]
  build-backend = "setuptools.build_meta"

[tool]
  [tool.setuptools]
    [tool.setuptools.package-data]
      osmit_gmbh_openziti = ["py.typed", "pulumi-plugin.json"]
