// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("openziti");

/**
 * Assimilate an existing object during create
 */
export declare const assimilate: string | undefined;
Object.defineProperty(exports, "assimilate", {
    get() {
        return __config.get("assimilate");
    },
    enumerable: true,
});

/**
 * The password. It is very secret.
 */
export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

/**
 * The URI to the API
 */
export declare const uri: string | undefined;
Object.defineProperty(exports, "uri", {
    get() {
        return __config.get("uri");
    },
    enumerable: true,
});

/**
 * The username. It's important but not secret.
 */
export declare const user: string | undefined;
Object.defineProperty(exports, "user", {
    get() {
        return __config.get("user");
    },
    enumerable: true,
});

export declare const version: string | undefined;
Object.defineProperty(exports, "version", {
    get() {
        return __config.get("version");
    },
    enumerable: true,
});

