// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace OsmitGmbh.Openziti.Outputs
{

    [OutputType]
    public sealed class EntityRef
    {
        public readonly ImmutableDictionary<string, Outputs.Link> _links;
        public readonly string? Entity;
        public readonly string? Name;
        public readonly string? ZitiId;

        [OutputConstructor]
        private EntityRef(
            ImmutableDictionary<string, Outputs.Link> _links,

            string? entity,

            string? name,

            string? zitiId)
        {
            this._links = _links;
            Entity = entity;
            Name = name;
            ZitiId = zitiId;
        }
    }
}
