// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace OsmitGmbh.Openziti.Outputs
{

    [OutputType]
    public sealed class IdentityEnrollmentsUpdb
    {
        public readonly string? ExpiresAt;
        public readonly string? Jwt;
        public readonly string? Token;
        public readonly string? ZitiId;

        [OutputConstructor]
        private IdentityEnrollmentsUpdb(
            string? expiresAt,

            string? jwt,

            string? token,

            string? zitiId)
        {
            ExpiresAt = expiresAt;
            Jwt = jwt;
            Token = token;
            ZitiId = zitiId;
        }
    }
}
