// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openziti.Outputs
{

    [OutputType]
    public sealed class IdentityEnrollmentsOttca
    {
        public readonly Outputs.EntityRef? Ca;
        public readonly string? CaId;
        public readonly string? ExpiresAt;
        public readonly string? Id;
        public readonly string? Jwt;
        public readonly string? Token;

        [OutputConstructor]
        private IdentityEnrollmentsOttca(
            Outputs.EntityRef? ca,

            string? caId,

            string? expiresAt,

            string? id,

            string? jwt,

            string? token)
        {
            Ca = ca;
            CaId = caId;
            ExpiresAt = expiresAt;
            Id = id;
            Jwt = jwt;
            Token = token;
        }
    }
}
