// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openziti.Outputs
{

    [OutputType]
    public sealed class IdentityEnrollments
    {
        public readonly Outputs.IdentityEnrollmentsOtt? Ott;
        public readonly Outputs.IdentityEnrollmentsOttca? Ottca;
        public readonly Outputs.IdentityEnrollmentsUpdb? Updb;

        [OutputConstructor]
        private IdentityEnrollments(
            Outputs.IdentityEnrollmentsOtt? ott,

            Outputs.IdentityEnrollmentsOttca? ottca,

            Outputs.IdentityEnrollmentsUpdb? updb)
        {
            Ott = ott;
            Ottca = ottca;
            Updb = updb;
        }
    }
}
