// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace OsmitGmbh.Openziti.Outputs
{

    [OutputType]
    public sealed class NamedRole
    {
        public readonly string? Name;
        public readonly string? Role;

        [OutputConstructor]
        private NamedRole(
            string? name,

            string? role)
        {
            Name = name;
            Role = role;
        }
    }
}
