// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openziti.Outputs
{

    [OutputType]
    public sealed class PostureQueriesType
    {
        public readonly bool IsPassing;
        public readonly string PolicyId;
        public readonly string? PolicyType;
        public readonly ImmutableArray<Pulumi.Openziti.Rest_model.Outputs.PostureQuery> PostureQueries;

        [OutputConstructor]
        private PostureQueriesType(
            bool isPassing,

            string policyId,

            string? policyType,

            ImmutableArray<Pulumi.Openziti.Rest_model.Outputs.PostureQuery> postureQueries)
        {
            IsPassing = isPassing;
            PolicyId = policyId;
            PolicyType = policyType;
            PostureQueries = postureQueries;
        }
    }
}
