# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .random import *
from .random_component import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import osmit_gmbh_openziti.config as __config
    config = __config
else:
    config = _utilities.lazy_import('osmit_gmbh_openziti.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "openziti",
  "mod": "index",
  "fqn": "osmit_gmbh_openziti",
  "classes": {
   "openziti:index:Random": "Random",
   "openziti:index:RandomComponent": "RandomComponent"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "openziti",
  "token": "pulumi:providers:openziti",
  "fqn": "osmit_gmbh_openziti",
  "class": "Provider"
 }
]
"""
)
