# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'IdentityCreateEnrollmentArgs',
    'IdentityCreateEnrollmentArgsDict',
]

class IdentityCreateEnrollmentArgsDict(TypedDict):
    ott: NotRequired[pulumi.Input[Optional[_builtins.bool]]]
    ottca: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    updb: NotRequired[pulumi.Input[Optional[_builtins.str]]]

@pulumi.input_type
class IdentityCreateEnrollmentArgs:
    def __init__(__self__, *,
                 ott: pulumi.Input[Optional[_builtins.bool]] = None,
                 ottca: pulumi.Input[Optional[_builtins.str]] = None,
                 updb: pulumi.Input[Optional[_builtins.str]] = None):
        if ott is not None:
            pulumi.set(__self__, "ott", ott)
        if ottca is not None:
            pulumi.set(__self__, "ottca", ottca)
        if updb is not None:
            pulumi.set(__self__, "updb", updb)

    @_builtins.property
    @pulumi.getter
    def ott(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "ott")

    @ott.setter
    def ott(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "ott", value)

    @_builtins.property
    @pulumi.getter
    def ottca(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ottca")

    @ottca.setter
    def ottca(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ottca", value)

    @_builtins.property
    @pulumi.getter
    def updb(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "updb")

    @updb.setter
    def updb(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updb", value)


