# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from . import rest_model as _rest_model
from ._inputs import *

__all__ = ['IdentityArgs', 'Identity']

@pulumi.input_type
class IdentityArgs:
    def __init__(__self__, *,
                 is_admin: pulumi.Input[_builtins.bool],
                 name: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str],
                 app_data: pulumi.Input[Optional[Mapping[str, Any]]] = None,
                 auth_policy_id: pulumi.Input[Optional[_builtins.str]] = None,
                 default_hosting_cost: pulumi.Input[Optional[_builtins.int]] = None,
                 default_hosting_precedence: pulumi.Input[Optional[_builtins.str]] = None,
                 enrollment: pulumi.Input[Optional['IdentityCreateEnrollmentArgs']] = None,
                 external_id: pulumi.Input[Optional[_builtins.str]] = None,
                 role_attributes: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 service_hosting_costs: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.int]]]] = None,
                 service_hosting_precedences: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, Any]]] = None):
        """
        The set of arguments for constructing a Identity resource.
        """
        pulumi.set(__self__, "is_admin", is_admin)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "type", type)
        if app_data is not None:
            pulumi.set(__self__, "app_data", app_data)
        if auth_policy_id is not None:
            pulumi.set(__self__, "auth_policy_id", auth_policy_id)
        if default_hosting_cost is not None:
            pulumi.set(__self__, "default_hosting_cost", default_hosting_cost)
        if default_hosting_precedence is not None:
            pulumi.set(__self__, "default_hosting_precedence", default_hosting_precedence)
        if enrollment is not None:
            pulumi.set(__self__, "enrollment", enrollment)
        if external_id is not None:
            pulumi.set(__self__, "external_id", external_id)
        if role_attributes is not None:
            pulumi.set(__self__, "role_attributes", role_attributes)
        if service_hosting_costs is not None:
            pulumi.set(__self__, "service_hosting_costs", service_hosting_costs)
        if service_hosting_precedences is not None:
            pulumi.set(__self__, "service_hosting_precedences", service_hosting_precedences)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter(name="isAdmin")
    def is_admin(self) -> pulumi.Input[_builtins.bool]:
        return pulumi.get(self, "is_admin")

    @is_admin.setter
    def is_admin(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "is_admin", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="appData")
    def app_data(self) -> pulumi.Input[Optional[Mapping[str, Any]]]:
        return pulumi.get(self, "app_data")

    @app_data.setter
    def app_data(self, value: pulumi.Input[Optional[Mapping[str, Any]]]):
        pulumi.set(self, "app_data", value)

    @_builtins.property
    @pulumi.getter(name="authPolicyId")
    def auth_policy_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "auth_policy_id")

    @auth_policy_id.setter
    def auth_policy_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "auth_policy_id", value)

    @_builtins.property
    @pulumi.getter(name="defaultHostingCost")
    def default_hosting_cost(self) -> pulumi.Input[Optional[_builtins.int]]:
        return pulumi.get(self, "default_hosting_cost")

    @default_hosting_cost.setter
    def default_hosting_cost(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "default_hosting_cost", value)

    @_builtins.property
    @pulumi.getter(name="defaultHostingPrecedence")
    def default_hosting_precedence(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "default_hosting_precedence")

    @default_hosting_precedence.setter
    def default_hosting_precedence(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "default_hosting_precedence", value)

    @_builtins.property
    @pulumi.getter
    def enrollment(self) -> pulumi.Input[Optional['IdentityCreateEnrollmentArgs']]:
        return pulumi.get(self, "enrollment")

    @enrollment.setter
    def enrollment(self, value: pulumi.Input[Optional['IdentityCreateEnrollmentArgs']]):
        pulumi.set(self, "enrollment", value)

    @_builtins.property
    @pulumi.getter(name="externalId")
    def external_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "external_id")

    @external_id.setter
    def external_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "external_id", value)

    @_builtins.property
    @pulumi.getter(name="roleAttributes")
    def role_attributes(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "role_attributes")

    @role_attributes.setter
    def role_attributes(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "role_attributes", value)

    @_builtins.property
    @pulumi.getter(name="serviceHostingCosts")
    def service_hosting_costs(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "service_hosting_costs")

    @service_hosting_costs.setter
    def service_hosting_costs(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "service_hosting_costs", value)

    @_builtins.property
    @pulumi.getter(name="serviceHostingPrecedences")
    def service_hosting_precedences(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "service_hosting_precedences")

    @service_hosting_precedences.setter
    def service_hosting_precedences(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "service_hosting_precedences", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Mapping[str, Any]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Mapping[str, Any]]]):
        pulumi.set(self, "tags", value)


@pulumi.type_token("openziti:index:Identity")
class Identity(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 app_data: pulumi.Input[Optional[Mapping[str, Any]]] = None,
                 auth_policy_id: pulumi.Input[Optional[_builtins.str]] = None,
                 default_hosting_cost: pulumi.Input[Optional[_builtins.int]] = None,
                 default_hosting_precedence: pulumi.Input[Optional[_builtins.str]] = None,
                 enrollment: pulumi.Input[Optional[Union['IdentityCreateEnrollmentArgs', 'IdentityCreateEnrollmentArgsDict']]] = None,
                 external_id: pulumi.Input[Optional[_builtins.str]] = None,
                 is_admin: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 role_attributes: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 service_hosting_costs: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.int]]]] = None,
                 service_hosting_precedences: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, Any]]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Identity resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: IdentityArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Identity resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param IdentityArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(IdentityArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 app_data: pulumi.Input[Optional[Mapping[str, Any]]] = None,
                 auth_policy_id: pulumi.Input[Optional[_builtins.str]] = None,
                 default_hosting_cost: pulumi.Input[Optional[_builtins.int]] = None,
                 default_hosting_precedence: pulumi.Input[Optional[_builtins.str]] = None,
                 enrollment: pulumi.Input[Optional[Union['IdentityCreateEnrollmentArgs', 'IdentityCreateEnrollmentArgsDict']]] = None,
                 external_id: pulumi.Input[Optional[_builtins.str]] = None,
                 is_admin: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 role_attributes: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 service_hosting_costs: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.int]]]] = None,
                 service_hosting_precedences: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, Any]]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = IdentityArgs.__new__(IdentityArgs)

            __props__.__dict__["app_data"] = app_data
            __props__.__dict__["auth_policy_id"] = auth_policy_id
            __props__.__dict__["default_hosting_cost"] = default_hosting_cost
            __props__.__dict__["default_hosting_precedence"] = default_hosting_precedence
            __props__.__dict__["enrollment"] = enrollment
            __props__.__dict__["external_id"] = external_id
            if is_admin is None and not opts.urn:
                raise TypeError("Missing required property 'is_admin'")
            __props__.__dict__["is_admin"] = is_admin
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["role_attributes"] = role_attributes
            __props__.__dict__["service_hosting_costs"] = service_hosting_costs
            __props__.__dict__["service_hosting_precedences"] = service_hosting_precedences
            __props__.__dict__["tags"] = tags
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            __props__.__dict__["_assimilated"] = None
            __props__.__dict__["_links"] = None
            __props__.__dict__["auth_policy"] = None
            __props__.__dict__["authenticators"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["disabled"] = None
            __props__.__dict__["disabled_at"] = None
            __props__.__dict__["disabled_until"] = None
            __props__.__dict__["env_info"] = None
            __props__.__dict__["has_api_session"] = None
            __props__.__dict__["has_edge_router_connection"] = None
            __props__.__dict__["is_default_admin"] = None
            __props__.__dict__["is_mfa_enabled"] = None
            __props__.__dict__["sdk_info"] = None
            __props__.__dict__["type_id"] = None
            __props__.__dict__["updated_at"] = None
            __props__.__dict__["ziti_id"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["enrollment"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Identity, __self__).__init__(
            'openziti:index:Identity',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Identity':
        """
        Get an existing Identity resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = IdentityArgs.__new__(IdentityArgs)

        __props__.__dict__["_assimilated"] = None
        __props__.__dict__["_links"] = None
        __props__.__dict__["app_data"] = None
        __props__.__dict__["auth_policy"] = None
        __props__.__dict__["auth_policy_id"] = None
        __props__.__dict__["authenticators"] = None
        __props__.__dict__["created_at"] = None
        __props__.__dict__["default_hosting_cost"] = None
        __props__.__dict__["default_hosting_precedence"] = None
        __props__.__dict__["disabled"] = None
        __props__.__dict__["disabled_at"] = None
        __props__.__dict__["disabled_until"] = None
        __props__.__dict__["enrollment"] = None
        __props__.__dict__["env_info"] = None
        __props__.__dict__["external_id"] = None
        __props__.__dict__["has_api_session"] = None
        __props__.__dict__["has_edge_router_connection"] = None
        __props__.__dict__["is_admin"] = None
        __props__.__dict__["is_default_admin"] = None
        __props__.__dict__["is_mfa_enabled"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["role_attributes"] = None
        __props__.__dict__["sdk_info"] = None
        __props__.__dict__["service_hosting_costs"] = None
        __props__.__dict__["service_hosting_precedences"] = None
        __props__.__dict__["tags"] = None
        __props__.__dict__["type"] = None
        __props__.__dict__["type_id"] = None
        __props__.__dict__["updated_at"] = None
        __props__.__dict__["ziti_id"] = None
        return Identity(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def _assimilated(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "_assimilated")

    @_builtins.property
    @pulumi.getter
    def _links(self) -> pulumi.Output[Mapping[str, 'outputs.Link']]:
        return pulumi.get(self, "_links")

    @_builtins.property
    @pulumi.getter(name="appData")
    def app_data(self) -> pulumi.Output[Optional[Mapping[str, Any]]]:
        return pulumi.get(self, "app_data")

    @_builtins.property
    @pulumi.getter(name="authPolicy")
    def auth_policy(self) -> pulumi.Output['outputs.EntityRef']:
        return pulumi.get(self, "auth_policy")

    @_builtins.property
    @pulumi.getter(name="authPolicyId")
    def auth_policy_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "auth_policy_id")

    @_builtins.property
    @pulumi.getter
    def authenticators(self) -> pulumi.Output['_rest_model.outputs.IdentityAuthenticators']:
        return pulumi.get(self, "authenticators")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="defaultHostingCost")
    def default_hosting_cost(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "default_hosting_cost")

    @_builtins.property
    @pulumi.getter(name="defaultHostingPrecedence")
    def default_hosting_precedence(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "default_hosting_precedence")

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "disabled")

    @_builtins.property
    @pulumi.getter(name="disabledAt")
    def disabled_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "disabled_at")

    @_builtins.property
    @pulumi.getter(name="disabledUntil")
    def disabled_until(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "disabled_until")

    @_builtins.property
    @pulumi.getter
    def enrollment(self) -> pulumi.Output['outputs.IdentityEnrollments']:
        return pulumi.get(self, "enrollment")

    @_builtins.property
    @pulumi.getter(name="envInfo")
    def env_info(self) -> pulumi.Output['outputs.EnvInfo']:
        return pulumi.get(self, "env_info")

    @_builtins.property
    @pulumi.getter(name="externalId")
    def external_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "external_id")

    @_builtins.property
    @pulumi.getter(name="hasApiSession")
    def has_api_session(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "has_api_session")

    @_builtins.property
    @pulumi.getter(name="hasEdgeRouterConnection")
    def has_edge_router_connection(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "has_edge_router_connection")

    @_builtins.property
    @pulumi.getter(name="isAdmin")
    def is_admin(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "is_admin")

    @_builtins.property
    @pulumi.getter(name="isDefaultAdmin")
    def is_default_admin(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "is_default_admin")

    @_builtins.property
    @pulumi.getter(name="isMfaEnabled")
    def is_mfa_enabled(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "is_mfa_enabled")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="roleAttributes")
    def role_attributes(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "role_attributes")

    @_builtins.property
    @pulumi.getter(name="sdkInfo")
    def sdk_info(self) -> pulumi.Output['outputs.SdkInfo']:
        return pulumi.get(self, "sdk_info")

    @_builtins.property
    @pulumi.getter(name="serviceHostingCosts")
    def service_hosting_costs(self) -> pulumi.Output[Mapping[str, _builtins.int]]:
        return pulumi.get(self, "service_hosting_costs")

    @_builtins.property
    @pulumi.getter(name="serviceHostingPrecedences")
    def service_hosting_precedences(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "service_hosting_precedences")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Mapping[str, Any]]]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output['outputs.EntityRef']:
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter(name="typeId")
    def type_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "type_id")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter(name="zitiId")
    def ziti_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "ziti_id")

