# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from . import rest_model as _rest_model

__all__ = [
    'EntityRef',
    'EnvInfo',
    'IdentityEnrollments',
    'IdentityEnrollmentsOtt',
    'IdentityEnrollmentsOttca',
    'IdentityEnrollmentsUpdb',
    'Link',
    'NamedRole',
    'PostureQueriesType',
    'SdkInfo',
]

@pulumi.output_type
class EntityRef(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "zitiId":
            suggest = "ziti_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in EntityRef. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        EntityRef.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        EntityRef.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 _links: Mapping[str, 'outputs.Link'],
                 entity: Optional[_builtins.str] = None,
                 name: Optional[_builtins.str] = None,
                 ziti_id: Optional[_builtins.str] = None):
        pulumi.set(__self__, "_links", _links)
        if entity is not None:
            pulumi.set(__self__, "entity", entity)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if ziti_id is not None:
            pulumi.set(__self__, "ziti_id", ziti_id)

    @_builtins.property
    @pulumi.getter
    def _links(self) -> Mapping[str, 'outputs.Link']:
        return pulumi.get(self, "_links")

    @_builtins.property
    @pulumi.getter
    def entity(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "entity")

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="zitiId")
    def ziti_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "ziti_id")


@pulumi.output_type
class EnvInfo(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "osRelease":
            suggest = "os_release"
        elif key == "osVersion":
            suggest = "os_version"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in EnvInfo. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        EnvInfo.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        EnvInfo.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 arch: Optional[_builtins.str] = None,
                 os: Optional[_builtins.str] = None,
                 os_release: Optional[_builtins.str] = None,
                 os_version: Optional[_builtins.str] = None):
        if arch is not None:
            pulumi.set(__self__, "arch", arch)
        if os is not None:
            pulumi.set(__self__, "os", os)
        if os_release is not None:
            pulumi.set(__self__, "os_release", os_release)
        if os_version is not None:
            pulumi.set(__self__, "os_version", os_version)

    @_builtins.property
    @pulumi.getter
    def arch(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "arch")

    @_builtins.property
    @pulumi.getter
    def os(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "os")

    @_builtins.property
    @pulumi.getter(name="osRelease")
    def os_release(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "os_release")

    @_builtins.property
    @pulumi.getter(name="osVersion")
    def os_version(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "os_version")


@pulumi.output_type
class IdentityEnrollments(dict):
    def __init__(__self__, *,
                 ott: Optional['outputs.IdentityEnrollmentsOtt'] = None,
                 ottca: Optional['outputs.IdentityEnrollmentsOttca'] = None,
                 updb: Optional['outputs.IdentityEnrollmentsUpdb'] = None):
        if ott is not None:
            pulumi.set(__self__, "ott", ott)
        if ottca is not None:
            pulumi.set(__self__, "ottca", ottca)
        if updb is not None:
            pulumi.set(__self__, "updb", updb)

    @_builtins.property
    @pulumi.getter
    def ott(self) -> Optional['outputs.IdentityEnrollmentsOtt']:
        return pulumi.get(self, "ott")

    @_builtins.property
    @pulumi.getter
    def ottca(self) -> Optional['outputs.IdentityEnrollmentsOttca']:
        return pulumi.get(self, "ottca")

    @_builtins.property
    @pulumi.getter
    def updb(self) -> Optional['outputs.IdentityEnrollmentsUpdb']:
        return pulumi.get(self, "updb")


@pulumi.output_type
class IdentityEnrollmentsOtt(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "expiresAt":
            suggest = "expires_at"
        elif key == "zitiId":
            suggest = "ziti_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in IdentityEnrollmentsOtt. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        IdentityEnrollmentsOtt.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        IdentityEnrollmentsOtt.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 expires_at: Optional[_builtins.str] = None,
                 jwt: Optional[_builtins.str] = None,
                 token: Optional[_builtins.str] = None,
                 ziti_id: Optional[_builtins.str] = None):
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if jwt is not None:
            pulumi.set(__self__, "jwt", jwt)
        if token is not None:
            pulumi.set(__self__, "token", token)
        if ziti_id is not None:
            pulumi.set(__self__, "ziti_id", ziti_id)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "expires_at")

    @_builtins.property
    @pulumi.getter
    def jwt(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "jwt")

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "token")

    @_builtins.property
    @pulumi.getter(name="zitiId")
    def ziti_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "ziti_id")


@pulumi.output_type
class IdentityEnrollmentsOttca(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "caId":
            suggest = "ca_id"
        elif key == "expiresAt":
            suggest = "expires_at"
        elif key == "zitiId":
            suggest = "ziti_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in IdentityEnrollmentsOttca. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        IdentityEnrollmentsOttca.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        IdentityEnrollmentsOttca.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 ca: Optional['outputs.EntityRef'] = None,
                 ca_id: Optional[_builtins.str] = None,
                 expires_at: Optional[_builtins.str] = None,
                 jwt: Optional[_builtins.str] = None,
                 token: Optional[_builtins.str] = None,
                 ziti_id: Optional[_builtins.str] = None):
        if ca is not None:
            pulumi.set(__self__, "ca", ca)
        if ca_id is not None:
            pulumi.set(__self__, "ca_id", ca_id)
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if jwt is not None:
            pulumi.set(__self__, "jwt", jwt)
        if token is not None:
            pulumi.set(__self__, "token", token)
        if ziti_id is not None:
            pulumi.set(__self__, "ziti_id", ziti_id)

    @_builtins.property
    @pulumi.getter
    def ca(self) -> Optional['outputs.EntityRef']:
        return pulumi.get(self, "ca")

    @_builtins.property
    @pulumi.getter(name="caId")
    def ca_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "ca_id")

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "expires_at")

    @_builtins.property
    @pulumi.getter
    def jwt(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "jwt")

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "token")

    @_builtins.property
    @pulumi.getter(name="zitiId")
    def ziti_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "ziti_id")


@pulumi.output_type
class IdentityEnrollmentsUpdb(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "expiresAt":
            suggest = "expires_at"
        elif key == "zitiId":
            suggest = "ziti_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in IdentityEnrollmentsUpdb. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        IdentityEnrollmentsUpdb.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        IdentityEnrollmentsUpdb.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 expires_at: Optional[_builtins.str] = None,
                 jwt: Optional[_builtins.str] = None,
                 token: Optional[_builtins.str] = None,
                 ziti_id: Optional[_builtins.str] = None):
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if jwt is not None:
            pulumi.set(__self__, "jwt", jwt)
        if token is not None:
            pulumi.set(__self__, "token", token)
        if ziti_id is not None:
            pulumi.set(__self__, "ziti_id", ziti_id)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "expires_at")

    @_builtins.property
    @pulumi.getter
    def jwt(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "jwt")

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "token")

    @_builtins.property
    @pulumi.getter(name="zitiId")
    def ziti_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "ziti_id")


@pulumi.output_type
class Link(dict):
    def __init__(__self__, *,
                 href: _builtins.str,
                 comment: Optional[_builtins.str] = None,
                 method: Optional[_builtins.str] = None):
        pulumi.set(__self__, "href", href)
        if comment is not None:
            pulumi.set(__self__, "comment", comment)
        if method is not None:
            pulumi.set(__self__, "method", method)

    @_builtins.property
    @pulumi.getter
    def href(self) -> _builtins.str:
        return pulumi.get(self, "href")

    @_builtins.property
    @pulumi.getter
    def comment(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "comment")

    @_builtins.property
    @pulumi.getter
    def method(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "method")


@pulumi.output_type
class NamedRole(dict):
    def __init__(__self__, *,
                 name: Optional[_builtins.str] = None,
                 role: Optional[_builtins.str] = None):
        if name is not None:
            pulumi.set(__self__, "name", name)
        if role is not None:
            pulumi.set(__self__, "role", role)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def role(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "role")


@pulumi.output_type
class PostureQueriesType(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "isPassing":
            suggest = "is_passing"
        elif key == "policyId":
            suggest = "policy_id"
        elif key == "postureQueries":
            suggest = "posture_queries"
        elif key == "policyType":
            suggest = "policy_type"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in PostureQueriesType. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        PostureQueriesType.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        PostureQueriesType.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 is_passing: _builtins.bool,
                 policy_id: _builtins.str,
                 posture_queries: Sequence['_rest_model.outputs.PostureQuery'],
                 policy_type: Optional[_builtins.str] = None):
        pulumi.set(__self__, "is_passing", is_passing)
        pulumi.set(__self__, "policy_id", policy_id)
        pulumi.set(__self__, "posture_queries", posture_queries)
        if policy_type is not None:
            pulumi.set(__self__, "policy_type", policy_type)

    @_builtins.property
    @pulumi.getter(name="isPassing")
    def is_passing(self) -> _builtins.bool:
        return pulumi.get(self, "is_passing")

    @_builtins.property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> _builtins.str:
        return pulumi.get(self, "policy_id")

    @_builtins.property
    @pulumi.getter(name="postureQueries")
    def posture_queries(self) -> Sequence['_rest_model.outputs.PostureQuery']:
        return pulumi.get(self, "posture_queries")

    @_builtins.property
    @pulumi.getter(name="policyType")
    def policy_type(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "policy_type")


@pulumi.output_type
class SdkInfo(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "appId":
            suggest = "app_id"
        elif key == "appVersion":
            suggest = "app_version"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in SdkInfo. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        SdkInfo.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        SdkInfo.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 app_id: Optional[_builtins.str] = None,
                 app_version: Optional[_builtins.str] = None,
                 branch: Optional[_builtins.str] = None,
                 revision: Optional[_builtins.str] = None,
                 type: Optional[_builtins.str] = None,
                 version: Optional[_builtins.str] = None):
        if app_id is not None:
            pulumi.set(__self__, "app_id", app_id)
        if app_version is not None:
            pulumi.set(__self__, "app_version", app_version)
        if branch is not None:
            pulumi.set(__self__, "branch", branch)
        if revision is not None:
            pulumi.set(__self__, "revision", revision)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter(name="appId")
    def app_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "app_id")

    @_builtins.property
    @pulumi.getter(name="appVersion")
    def app_version(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "app_version")

    @_builtins.property
    @pulumi.getter
    def branch(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "branch")

    @_builtins.property
    @pulumi.getter
    def revision(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "revision")

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "version")


