# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from . import rest_model as _rest_model

__all__ = ['ServiceArgs', 'Service']

@pulumi.input_type
class ServiceArgs:
    def __init__(__self__, *,
                 configs: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 encryption_required: pulumi.Input[_builtins.bool],
                 name: pulumi.Input[_builtins.str],
                 role_attributes: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 tags: pulumi.Input[Optional[Mapping[str, Any]]] = None,
                 terminator_strategy: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Service resource.
        """
        pulumi.set(__self__, "configs", configs)
        pulumi.set(__self__, "encryption_required", encryption_required)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "role_attributes", role_attributes)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if terminator_strategy is not None:
            pulumi.set(__self__, "terminator_strategy", terminator_strategy)

    @_builtins.property
    @pulumi.getter
    def configs(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        return pulumi.get(self, "configs")

    @configs.setter
    def configs(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "configs", value)

    @_builtins.property
    @pulumi.getter(name="encryptionRequired")
    def encryption_required(self) -> pulumi.Input[_builtins.bool]:
        return pulumi.get(self, "encryption_required")

    @encryption_required.setter
    def encryption_required(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "encryption_required", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="roleAttributes")
    def role_attributes(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        return pulumi.get(self, "role_attributes")

    @role_attributes.setter
    def role_attributes(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "role_attributes", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Mapping[str, Any]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Mapping[str, Any]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="terminatorStrategy")
    def terminator_strategy(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "terminator_strategy")

    @terminator_strategy.setter
    def terminator_strategy(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "terminator_strategy", value)


@pulumi.type_token("openziti:index:Service")
class Service(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 configs: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 encryption_required: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 role_attributes: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, Any]]] = None,
                 terminator_strategy: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Service resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ServiceArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Service resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ServiceArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ServiceArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 configs: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 encryption_required: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 role_attributes: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, Any]]] = None,
                 terminator_strategy: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ServiceArgs.__new__(ServiceArgs)

            if configs is None and not opts.urn:
                raise TypeError("Missing required property 'configs'")
            __props__.__dict__["configs"] = configs
            if encryption_required is None and not opts.urn:
                raise TypeError("Missing required property 'encryption_required'")
            __props__.__dict__["encryption_required"] = encryption_required
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if role_attributes is None and not opts.urn:
                raise TypeError("Missing required property 'role_attributes'")
            __props__.__dict__["role_attributes"] = role_attributes
            __props__.__dict__["tags"] = tags
            __props__.__dict__["terminator_strategy"] = terminator_strategy
            __props__.__dict__["_assimilated"] = None
            __props__.__dict__["_links"] = None
            __props__.__dict__["config"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["permissions"] = None
            __props__.__dict__["posture_queries"] = None
            __props__.__dict__["updated_at"] = None
            __props__.__dict__["ziti_id"] = None
        super(Service, __self__).__init__(
            'openziti:index:Service',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Service':
        """
        Get an existing Service resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ServiceArgs.__new__(ServiceArgs)

        __props__.__dict__["_assimilated"] = None
        __props__.__dict__["_links"] = None
        __props__.__dict__["config"] = None
        __props__.__dict__["configs"] = None
        __props__.__dict__["created_at"] = None
        __props__.__dict__["encryption_required"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["permissions"] = None
        __props__.__dict__["posture_queries"] = None
        __props__.__dict__["role_attributes"] = None
        __props__.__dict__["tags"] = None
        __props__.__dict__["terminator_strategy"] = None
        __props__.__dict__["updated_at"] = None
        __props__.__dict__["ziti_id"] = None
        return Service(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def _assimilated(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "_assimilated")

    @_builtins.property
    @pulumi.getter
    def _links(self) -> pulumi.Output[Mapping[str, 'outputs.Link']]:
        return pulumi.get(self, "_links")

    @_builtins.property
    @pulumi.getter
    def config(self) -> pulumi.Output[Mapping[str, Mapping[str, Any]]]:
        return pulumi.get(self, "config")

    @_builtins.property
    @pulumi.getter
    def configs(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "configs")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="encryptionRequired")
    def encryption_required(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "encryption_required")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def permissions(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "permissions")

    @_builtins.property
    @pulumi.getter(name="postureQueries")
    def posture_queries(self) -> pulumi.Output[Sequence['outputs.PostureQueriesType']]:
        return pulumi.get(self, "posture_queries")

    @_builtins.property
    @pulumi.getter(name="roleAttributes")
    def role_attributes(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "role_attributes")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Mapping[str, Any]]]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="terminatorStrategy")
    def terminator_strategy(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "terminator_strategy")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter(name="zitiId")
    def ziti_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "ziti_id")

