// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.openziti;

import com.osmitgmbh.openziti.EnrolledIdentityArgs;
import com.osmitgmbh.openziti.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

@ResourceType(type="openziti:index:EnrolledIdentity")
public class EnrolledIdentity extends com.pulumi.resources.CustomResource {
    @Export(name="enrollmentJwt", refs={String.class}, tree="[0]")
    private Output<String> enrollmentJwt;

    public Output<String> enrollmentJwt() {
        return this.enrollmentJwt;
    }
    @Export(name="identityJson", refs={String.class}, tree="[0]")
    private Output<String> identityJson;

    public Output<String> identityJson() {
        return this.identityJson;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public EnrolledIdentity(java.lang.String name) {
        this(name, EnrolledIdentityArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public EnrolledIdentity(java.lang.String name, EnrolledIdentityArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public EnrolledIdentity(java.lang.String name, EnrolledIdentityArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("openziti:index:EnrolledIdentity", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private EnrolledIdentity(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("openziti:index:EnrolledIdentity", name, null, makeResourceOptions(options, id), false);
    }

    private static EnrolledIdentityArgs makeArgs(EnrolledIdentityArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? EnrolledIdentityArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "enrollmentJwt",
                "identityJson"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static EnrolledIdentity get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new EnrolledIdentity(name, id, options);
    }
}
