// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.openziti;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServiceEdgeRouterPolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServiceEdgeRouterPolicyArgs Empty = new ServiceEdgeRouterPolicyArgs();

    @Import(name="edgeRouterRoles")
    private @Nullable Output<List<String>> edgeRouterRoles;

    public Optional<Output<List<String>>> edgeRouterRoles() {
        return Optional.ofNullable(this.edgeRouterRoles);
    }

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="semantic", required=true)
    private Output<String> semantic;

    public Output<String> semantic() {
        return this.semantic;
    }

    @Import(name="serviceRoles", required=true)
    private Output<List<String>> serviceRoles;

    public Output<List<String>> serviceRoles() {
        return this.serviceRoles;
    }

    @Import(name="tags")
    private @Nullable Output<Map<String,Object>> tags;

    public Optional<Output<Map<String,Object>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    private ServiceEdgeRouterPolicyArgs() {}

    private ServiceEdgeRouterPolicyArgs(ServiceEdgeRouterPolicyArgs $) {
        this.edgeRouterRoles = $.edgeRouterRoles;
        this.name = $.name;
        this.semantic = $.semantic;
        this.serviceRoles = $.serviceRoles;
        this.tags = $.tags;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServiceEdgeRouterPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServiceEdgeRouterPolicyArgs $;

        public Builder() {
            $ = new ServiceEdgeRouterPolicyArgs();
        }

        public Builder(ServiceEdgeRouterPolicyArgs defaults) {
            $ = new ServiceEdgeRouterPolicyArgs(Objects.requireNonNull(defaults));
        }

        public Builder edgeRouterRoles(@Nullable Output<List<String>> edgeRouterRoles) {
            $.edgeRouterRoles = edgeRouterRoles;
            return this;
        }

        public Builder edgeRouterRoles(List<String> edgeRouterRoles) {
            return edgeRouterRoles(Output.of(edgeRouterRoles));
        }

        public Builder edgeRouterRoles(String... edgeRouterRoles) {
            return edgeRouterRoles(List.of(edgeRouterRoles));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder semantic(Output<String> semantic) {
            $.semantic = semantic;
            return this;
        }

        public Builder semantic(String semantic) {
            return semantic(Output.of(semantic));
        }

        public Builder serviceRoles(Output<List<String>> serviceRoles) {
            $.serviceRoles = serviceRoles;
            return this;
        }

        public Builder serviceRoles(List<String> serviceRoles) {
            return serviceRoles(Output.of(serviceRoles));
        }

        public Builder serviceRoles(String... serviceRoles) {
            return serviceRoles(List.of(serviceRoles));
        }

        public Builder tags(@Nullable Output<Map<String,Object>> tags) {
            $.tags = tags;
            return this;
        }

        public Builder tags(Map<String,Object> tags) {
            return tags(Output.of(tags));
        }

        public ServiceEdgeRouterPolicyArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("ServiceEdgeRouterPolicyArgs", "name");
            }
            if ($.semantic == null) {
                throw new MissingRequiredPropertyException("ServiceEdgeRouterPolicyArgs", "semantic");
            }
            if ($.serviceRoles == null) {
                throw new MissingRequiredPropertyException("ServiceEdgeRouterPolicyArgs", "serviceRoles");
            }
            return $;
        }
    }

}
