// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.openziti;

import com.osmitgmbh.openziti.ServicePolicyArgs;
import com.osmitgmbh.openziti.Utilities;
import com.osmitgmbh.openziti.outputs.Link;
import com.osmitgmbh.openziti.outputs.NamedRole;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="openziti:index:ServicePolicy")
public class ServicePolicy extends com.pulumi.resources.CustomResource {
    @Export(name="_assimilated", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> _assimilated;

    public Output<Boolean> _assimilated() {
        return this._assimilated;
    }
    @Export(name="_links", refs={Map.class,String.class,Link.class}, tree="[0,1,2]")
    private Output<Map<String,Link>> _links;

    public Output<Map<String,Link>> _links() {
        return this._links;
    }
    @Export(name="createdAt", refs={String.class}, tree="[0]")
    private Output<String> createdAt;

    public Output<String> createdAt() {
        return this.createdAt;
    }
    @Export(name="identityRoles", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> identityRoles;

    public Output<List<String>> identityRoles() {
        return this.identityRoles;
    }
    @Export(name="identityRolesDisplay", refs={List.class,NamedRole.class}, tree="[0,1]")
    private Output<List<NamedRole>> identityRolesDisplay;

    public Output<List<NamedRole>> identityRolesDisplay() {
        return this.identityRolesDisplay;
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="postureCheckRoles", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> postureCheckRoles;

    public Output<List<String>> postureCheckRoles() {
        return this.postureCheckRoles;
    }
    @Export(name="postureCheckRolesDisplay", refs={List.class,NamedRole.class}, tree="[0,1]")
    private Output<List<NamedRole>> postureCheckRolesDisplay;

    public Output<List<NamedRole>> postureCheckRolesDisplay() {
        return this.postureCheckRolesDisplay;
    }
    @Export(name="semantic", refs={String.class}, tree="[0]")
    private Output<String> semantic;

    public Output<String> semantic() {
        return this.semantic;
    }
    @Export(name="serviceRoles", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> serviceRoles;

    public Output<List<String>> serviceRoles() {
        return this.serviceRoles;
    }
    @Export(name="serviceRolesDisplay", refs={List.class,NamedRole.class}, tree="[0,1]")
    private Output<List<NamedRole>> serviceRolesDisplay;

    public Output<List<NamedRole>> serviceRolesDisplay() {
        return this.serviceRolesDisplay;
    }
    @Export(name="tags", refs={Map.class,String.class,Object.class}, tree="[0,1,2]")
    private Output</* @Nullable */ Map<String,Object>> tags;

    public Output<Optional<Map<String,Object>>> tags() {
        return Codegen.optional(this.tags);
    }
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    public Output<String> type() {
        return this.type;
    }
    @Export(name="updatedAt", refs={String.class}, tree="[0]")
    private Output<String> updatedAt;

    public Output<String> updatedAt() {
        return this.updatedAt;
    }
    @Export(name="zitiId", refs={String.class}, tree="[0]")
    private Output<String> zitiId;

    public Output<String> zitiId() {
        return this.zitiId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ServicePolicy(java.lang.String name) {
        this(name, ServicePolicyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ServicePolicy(java.lang.String name, ServicePolicyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ServicePolicy(java.lang.String name, ServicePolicyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("openziti:index:ServicePolicy", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ServicePolicy(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("openziti:index:ServicePolicy", name, null, makeResourceOptions(options, id), false);
    }

    private static ServicePolicyArgs makeArgs(ServicePolicyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ServicePolicyArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ServicePolicy get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ServicePolicy(name, id, options);
    }
}
