// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.openziti;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServicePolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServicePolicyArgs Empty = new ServicePolicyArgs();

    @Import(name="identityRoles", required=true)
    private Output<List<String>> identityRoles;

    public Output<List<String>> identityRoles() {
        return this.identityRoles;
    }

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="postureCheckRoles")
    private @Nullable Output<List<String>> postureCheckRoles;

    public Optional<Output<List<String>>> postureCheckRoles() {
        return Optional.ofNullable(this.postureCheckRoles);
    }

    @Import(name="semantic", required=true)
    private Output<String> semantic;

    public Output<String> semantic() {
        return this.semantic;
    }

    @Import(name="serviceRoles", required=true)
    private Output<List<String>> serviceRoles;

    public Output<List<String>> serviceRoles() {
        return this.serviceRoles;
    }

    @Import(name="tags")
    private @Nullable Output<Map<String,Object>> tags;

    public Optional<Output<Map<String,Object>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    @Import(name="type", required=true)
    private Output<String> type;

    public Output<String> type() {
        return this.type;
    }

    private ServicePolicyArgs() {}

    private ServicePolicyArgs(ServicePolicyArgs $) {
        this.identityRoles = $.identityRoles;
        this.name = $.name;
        this.postureCheckRoles = $.postureCheckRoles;
        this.semantic = $.semantic;
        this.serviceRoles = $.serviceRoles;
        this.tags = $.tags;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServicePolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServicePolicyArgs $;

        public Builder() {
            $ = new ServicePolicyArgs();
        }

        public Builder(ServicePolicyArgs defaults) {
            $ = new ServicePolicyArgs(Objects.requireNonNull(defaults));
        }

        public Builder identityRoles(Output<List<String>> identityRoles) {
            $.identityRoles = identityRoles;
            return this;
        }

        public Builder identityRoles(List<String> identityRoles) {
            return identityRoles(Output.of(identityRoles));
        }

        public Builder identityRoles(String... identityRoles) {
            return identityRoles(List.of(identityRoles));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder postureCheckRoles(@Nullable Output<List<String>> postureCheckRoles) {
            $.postureCheckRoles = postureCheckRoles;
            return this;
        }

        public Builder postureCheckRoles(List<String> postureCheckRoles) {
            return postureCheckRoles(Output.of(postureCheckRoles));
        }

        public Builder postureCheckRoles(String... postureCheckRoles) {
            return postureCheckRoles(List.of(postureCheckRoles));
        }

        public Builder semantic(Output<String> semantic) {
            $.semantic = semantic;
            return this;
        }

        public Builder semantic(String semantic) {
            return semantic(Output.of(semantic));
        }

        public Builder serviceRoles(Output<List<String>> serviceRoles) {
            $.serviceRoles = serviceRoles;
            return this;
        }

        public Builder serviceRoles(List<String> serviceRoles) {
            return serviceRoles(Output.of(serviceRoles));
        }

        public Builder serviceRoles(String... serviceRoles) {
            return serviceRoles(List.of(serviceRoles));
        }

        public Builder tags(@Nullable Output<Map<String,Object>> tags) {
            $.tags = tags;
            return this;
        }

        public Builder tags(Map<String,Object> tags) {
            return tags(Output.of(tags));
        }

        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public ServicePolicyArgs build() {
            if ($.identityRoles == null) {
                throw new MissingRequiredPropertyException("ServicePolicyArgs", "identityRoles");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("ServicePolicyArgs", "name");
            }
            if ($.semantic == null) {
                throw new MissingRequiredPropertyException("ServicePolicyArgs", "semantic");
            }
            if ($.serviceRoles == null) {
                throw new MissingRequiredPropertyException("ServicePolicyArgs", "serviceRoles");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("ServicePolicyArgs", "type");
            }
            return $;
        }
    }

}
