// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.openziti.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class EnvInfo {
    private @Nullable String arch;
    private @Nullable String os;
    private @Nullable String osRelease;
    private @Nullable String osVersion;

    private EnvInfo() {}
    public Optional<String> arch() {
        return Optional.ofNullable(this.arch);
    }
    public Optional<String> os() {
        return Optional.ofNullable(this.os);
    }
    public Optional<String> osRelease() {
        return Optional.ofNullable(this.osRelease);
    }
    public Optional<String> osVersion() {
        return Optional.ofNullable(this.osVersion);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(EnvInfo defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String arch;
        private @Nullable String os;
        private @Nullable String osRelease;
        private @Nullable String osVersion;
        public Builder() {}
        public Builder(EnvInfo defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.arch = defaults.arch;
    	      this.os = defaults.os;
    	      this.osRelease = defaults.osRelease;
    	      this.osVersion = defaults.osVersion;
        }

        @CustomType.Setter
        public Builder arch(@Nullable String arch) {

            this.arch = arch;
            return this;
        }
        @CustomType.Setter
        public Builder os(@Nullable String os) {

            this.os = os;
            return this;
        }
        @CustomType.Setter
        public Builder osRelease(@Nullable String osRelease) {

            this.osRelease = osRelease;
            return this;
        }
        @CustomType.Setter
        public Builder osVersion(@Nullable String osVersion) {

            this.osVersion = osVersion;
            return this;
        }
        public EnvInfo build() {
            final var _resultValue = new EnvInfo();
            _resultValue.arch = arch;
            _resultValue.os = os;
            _resultValue.osRelease = osRelease;
            _resultValue.osVersion = osVersion;
            return _resultValue;
        }
    }
}
