// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.openziti.outputs;

import com.osmitgmbh.openziti.outputs.EntityRef;
import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class IdentityEnrollmentsOttca {
    private @Nullable EntityRef ca;
    private @Nullable String caId;
    private @Nullable String expiresAt;
    private @Nullable String jwt;
    private @Nullable String token;
    private @Nullable String zitiId;

    private IdentityEnrollmentsOttca() {}
    public Optional<EntityRef> ca() {
        return Optional.ofNullable(this.ca);
    }
    public Optional<String> caId() {
        return Optional.ofNullable(this.caId);
    }
    public Optional<String> expiresAt() {
        return Optional.ofNullable(this.expiresAt);
    }
    public Optional<String> jwt() {
        return Optional.ofNullable(this.jwt);
    }
    public Optional<String> token() {
        return Optional.ofNullable(this.token);
    }
    public Optional<String> zitiId() {
        return Optional.ofNullable(this.zitiId);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(IdentityEnrollmentsOttca defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable EntityRef ca;
        private @Nullable String caId;
        private @Nullable String expiresAt;
        private @Nullable String jwt;
        private @Nullable String token;
        private @Nullable String zitiId;
        public Builder() {}
        public Builder(IdentityEnrollmentsOttca defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ca = defaults.ca;
    	      this.caId = defaults.caId;
    	      this.expiresAt = defaults.expiresAt;
    	      this.jwt = defaults.jwt;
    	      this.token = defaults.token;
    	      this.zitiId = defaults.zitiId;
        }

        @CustomType.Setter
        public Builder ca(@Nullable EntityRef ca) {

            this.ca = ca;
            return this;
        }
        @CustomType.Setter
        public Builder caId(@Nullable String caId) {

            this.caId = caId;
            return this;
        }
        @CustomType.Setter
        public Builder expiresAt(@Nullable String expiresAt) {

            this.expiresAt = expiresAt;
            return this;
        }
        @CustomType.Setter
        public Builder jwt(@Nullable String jwt) {

            this.jwt = jwt;
            return this;
        }
        @CustomType.Setter
        public Builder token(@Nullable String token) {

            this.token = token;
            return this;
        }
        @CustomType.Setter
        public Builder zitiId(@Nullable String zitiId) {

            this.zitiId = zitiId;
            return this;
        }
        public IdentityEnrollmentsOttca build() {
            final var _resultValue = new IdentityEnrollmentsOttca();
            _resultValue.ca = ca;
            _resultValue.caId = caId;
            _resultValue.expiresAt = expiresAt;
            _resultValue.jwt = jwt;
            _resultValue.token = token;
            _resultValue.zitiId = zitiId;
            return _resultValue;
        }
    }
}
