// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.openziti.outputs;

import com.osmitgmbh.openziti.rest_model.outputs.PostureQuery;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class PostureQueriesType {
    private Boolean isPassing;
    private String policyId;
    private @Nullable String policyType;
    private List<PostureQuery> postureQueries;

    private PostureQueriesType() {}
    public Boolean isPassing() {
        return this.isPassing;
    }
    public String policyId() {
        return this.policyId;
    }
    public Optional<String> policyType() {
        return Optional.ofNullable(this.policyType);
    }
    public List<PostureQuery> postureQueries() {
        return this.postureQueries;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PostureQueriesType defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean isPassing;
        private String policyId;
        private @Nullable String policyType;
        private List<PostureQuery> postureQueries;
        public Builder() {}
        public Builder(PostureQueriesType defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.isPassing = defaults.isPassing;
    	      this.policyId = defaults.policyId;
    	      this.policyType = defaults.policyType;
    	      this.postureQueries = defaults.postureQueries;
        }

        @CustomType.Setter
        public Builder isPassing(Boolean isPassing) {
            if (isPassing == null) {
              throw new MissingRequiredPropertyException("PostureQueriesType", "isPassing");
            }
            this.isPassing = isPassing;
            return this;
        }
        @CustomType.Setter
        public Builder policyId(String policyId) {
            if (policyId == null) {
              throw new MissingRequiredPropertyException("PostureQueriesType", "policyId");
            }
            this.policyId = policyId;
            return this;
        }
        @CustomType.Setter
        public Builder policyType(@Nullable String policyType) {

            this.policyType = policyType;
            return this;
        }
        @CustomType.Setter
        public Builder postureQueries(List<PostureQuery> postureQueries) {
            if (postureQueries == null) {
              throw new MissingRequiredPropertyException("PostureQueriesType", "postureQueries");
            }
            this.postureQueries = postureQueries;
            return this;
        }
        public Builder postureQueries(PostureQuery... postureQueries) {
            return postureQueries(List.of(postureQueries));
        }
        public PostureQueriesType build() {
            final var _resultValue = new PostureQueriesType();
            _resultValue.isPassing = isPassing;
            _resultValue.policyId = policyId;
            _resultValue.policyType = policyType;
            _resultValue.postureQueries = postureQueries;
            return _resultValue;
        }
    }
}
