// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.openziti.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SdkInfo {
    private @Nullable String appId;
    private @Nullable String appVersion;
    private @Nullable String branch;
    private @Nullable String revision;
    private @Nullable String type;
    private @Nullable String version;

    private SdkInfo() {}
    public Optional<String> appId() {
        return Optional.ofNullable(this.appId);
    }
    public Optional<String> appVersion() {
        return Optional.ofNullable(this.appVersion);
    }
    public Optional<String> branch() {
        return Optional.ofNullable(this.branch);
    }
    public Optional<String> revision() {
        return Optional.ofNullable(this.revision);
    }
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SdkInfo defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String appId;
        private @Nullable String appVersion;
        private @Nullable String branch;
        private @Nullable String revision;
        private @Nullable String type;
        private @Nullable String version;
        public Builder() {}
        public Builder(SdkInfo defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.appId = defaults.appId;
    	      this.appVersion = defaults.appVersion;
    	      this.branch = defaults.branch;
    	      this.revision = defaults.revision;
    	      this.type = defaults.type;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder appId(@Nullable String appId) {

            this.appId = appId;
            return this;
        }
        @CustomType.Setter
        public Builder appVersion(@Nullable String appVersion) {

            this.appVersion = appVersion;
            return this;
        }
        @CustomType.Setter
        public Builder branch(@Nullable String branch) {

            this.branch = branch;
            return this;
        }
        @CustomType.Setter
        public Builder revision(@Nullable String revision) {

            this.revision = revision;
            return this;
        }
        @CustomType.Setter
        public Builder type(@Nullable String type) {

            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder version(@Nullable String version) {

            this.version = version;
            return this;
        }
        public SdkInfo build() {
            final var _resultValue = new SdkInfo();
            _resultValue.appId = appId;
            _resultValue.appVersion = appVersion;
            _resultValue.branch = branch;
            _resultValue.revision = revision;
            _resultValue.type = type;
            _resultValue.version = version;
            return _resultValue;
        }
    }
}
