// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumiopenziti

import (
	"context"
	"reflect"

	"errors"
	"github.com/OSMIT-GmbH/pulumi-openziti/sdk/go/pulumi-openziti/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type EdgeRouterPolicy struct {
	pulumi.CustomResourceState

	_assimilated           pulumi.BoolOutput        `pulumi:"_assimilated"`
	_links                 LinkMapOutput            `pulumi:"_links"`
	CreatedAt              pulumi.StringOutput      `pulumi:"createdAt"`
	EdgeRouterRoles        pulumi.StringArrayOutput `pulumi:"edgeRouterRoles"`
	EdgeRouterRolesDisplay NamedRoleArrayOutput     `pulumi:"edgeRouterRolesDisplay"`
	IdentityRoles          pulumi.StringArrayOutput `pulumi:"identityRoles"`
	IdentityRolesDisplay   NamedRoleArrayOutput     `pulumi:"identityRolesDisplay"`
	Name                   pulumi.StringOutput      `pulumi:"name"`
	Semantic               pulumi.StringOutput      `pulumi:"semantic"`
	Tags                   pulumi.MapOutput         `pulumi:"tags"`
	UpdatedAt              pulumi.StringOutput      `pulumi:"updatedAt"`
	ZitiId                 pulumi.StringOutput      `pulumi:"zitiId"`
}

// NewEdgeRouterPolicy registers a new resource with the given unique name, arguments, and options.
func NewEdgeRouterPolicy(ctx *pulumi.Context,
	name string, args *EdgeRouterPolicyArgs, opts ...pulumi.ResourceOption) (*EdgeRouterPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.IdentityRoles == nil {
		return nil, errors.New("invalid value for required argument 'IdentityRoles'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Semantic == nil {
		return nil, errors.New("invalid value for required argument 'Semantic'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource EdgeRouterPolicy
	err := ctx.RegisterResource("openziti:index:EdgeRouterPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEdgeRouterPolicy gets an existing EdgeRouterPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEdgeRouterPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EdgeRouterPolicyState, opts ...pulumi.ResourceOption) (*EdgeRouterPolicy, error) {
	var resource EdgeRouterPolicy
	err := ctx.ReadResource("openziti:index:EdgeRouterPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering EdgeRouterPolicy resources.
type edgeRouterPolicyState struct {
}

type EdgeRouterPolicyState struct {
}

func (EdgeRouterPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*edgeRouterPolicyState)(nil)).Elem()
}

type edgeRouterPolicyArgs struct {
	EdgeRouterRoles []string               `pulumi:"edgeRouterRoles"`
	IdentityRoles   []string               `pulumi:"identityRoles"`
	Name            string                 `pulumi:"name"`
	Semantic        string                 `pulumi:"semantic"`
	Tags            map[string]interface{} `pulumi:"tags"`
}

// The set of arguments for constructing a EdgeRouterPolicy resource.
type EdgeRouterPolicyArgs struct {
	EdgeRouterRoles pulumi.StringArrayInput
	IdentityRoles   pulumi.StringArrayInput
	Name            pulumi.StringInput
	Semantic        pulumi.StringInput
	Tags            pulumi.MapInput
}

func (EdgeRouterPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*edgeRouterPolicyArgs)(nil)).Elem()
}

type EdgeRouterPolicyInput interface {
	pulumi.Input

	ToEdgeRouterPolicyOutput() EdgeRouterPolicyOutput
	ToEdgeRouterPolicyOutputWithContext(ctx context.Context) EdgeRouterPolicyOutput
}

func (*EdgeRouterPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**EdgeRouterPolicy)(nil)).Elem()
}

func (i *EdgeRouterPolicy) ToEdgeRouterPolicyOutput() EdgeRouterPolicyOutput {
	return i.ToEdgeRouterPolicyOutputWithContext(context.Background())
}

func (i *EdgeRouterPolicy) ToEdgeRouterPolicyOutputWithContext(ctx context.Context) EdgeRouterPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EdgeRouterPolicyOutput)
}

// EdgeRouterPolicyArrayInput is an input type that accepts EdgeRouterPolicyArray and EdgeRouterPolicyArrayOutput values.
// You can construct a concrete instance of `EdgeRouterPolicyArrayInput` via:
//
//	EdgeRouterPolicyArray{ EdgeRouterPolicyArgs{...} }
type EdgeRouterPolicyArrayInput interface {
	pulumi.Input

	ToEdgeRouterPolicyArrayOutput() EdgeRouterPolicyArrayOutput
	ToEdgeRouterPolicyArrayOutputWithContext(context.Context) EdgeRouterPolicyArrayOutput
}

type EdgeRouterPolicyArray []EdgeRouterPolicyInput

func (EdgeRouterPolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EdgeRouterPolicy)(nil)).Elem()
}

func (i EdgeRouterPolicyArray) ToEdgeRouterPolicyArrayOutput() EdgeRouterPolicyArrayOutput {
	return i.ToEdgeRouterPolicyArrayOutputWithContext(context.Background())
}

func (i EdgeRouterPolicyArray) ToEdgeRouterPolicyArrayOutputWithContext(ctx context.Context) EdgeRouterPolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EdgeRouterPolicyArrayOutput)
}

// EdgeRouterPolicyMapInput is an input type that accepts EdgeRouterPolicyMap and EdgeRouterPolicyMapOutput values.
// You can construct a concrete instance of `EdgeRouterPolicyMapInput` via:
//
//	EdgeRouterPolicyMap{ "key": EdgeRouterPolicyArgs{...} }
type EdgeRouterPolicyMapInput interface {
	pulumi.Input

	ToEdgeRouterPolicyMapOutput() EdgeRouterPolicyMapOutput
	ToEdgeRouterPolicyMapOutputWithContext(context.Context) EdgeRouterPolicyMapOutput
}

type EdgeRouterPolicyMap map[string]EdgeRouterPolicyInput

func (EdgeRouterPolicyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EdgeRouterPolicy)(nil)).Elem()
}

func (i EdgeRouterPolicyMap) ToEdgeRouterPolicyMapOutput() EdgeRouterPolicyMapOutput {
	return i.ToEdgeRouterPolicyMapOutputWithContext(context.Background())
}

func (i EdgeRouterPolicyMap) ToEdgeRouterPolicyMapOutputWithContext(ctx context.Context) EdgeRouterPolicyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EdgeRouterPolicyMapOutput)
}

type EdgeRouterPolicyOutput struct{ *pulumi.OutputState }

func (EdgeRouterPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EdgeRouterPolicy)(nil)).Elem()
}

func (o EdgeRouterPolicyOutput) ToEdgeRouterPolicyOutput() EdgeRouterPolicyOutput {
	return o
}

func (o EdgeRouterPolicyOutput) ToEdgeRouterPolicyOutputWithContext(ctx context.Context) EdgeRouterPolicyOutput {
	return o
}

func (o EdgeRouterPolicyOutput) _assimilated() pulumi.BoolOutput {
	return o.ApplyT(func(v *EdgeRouterPolicy) pulumi.BoolOutput { return v._assimilated }).(pulumi.BoolOutput)
}

func (o EdgeRouterPolicyOutput) _links() LinkMapOutput {
	return o.ApplyT(func(v *EdgeRouterPolicy) LinkMapOutput { return v._links }).(LinkMapOutput)
}

func (o EdgeRouterPolicyOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *EdgeRouterPolicy) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o EdgeRouterPolicyOutput) EdgeRouterRoles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *EdgeRouterPolicy) pulumi.StringArrayOutput { return v.EdgeRouterRoles }).(pulumi.StringArrayOutput)
}

func (o EdgeRouterPolicyOutput) EdgeRouterRolesDisplay() NamedRoleArrayOutput {
	return o.ApplyT(func(v *EdgeRouterPolicy) NamedRoleArrayOutput { return v.EdgeRouterRolesDisplay }).(NamedRoleArrayOutput)
}

func (o EdgeRouterPolicyOutput) IdentityRoles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *EdgeRouterPolicy) pulumi.StringArrayOutput { return v.IdentityRoles }).(pulumi.StringArrayOutput)
}

func (o EdgeRouterPolicyOutput) IdentityRolesDisplay() NamedRoleArrayOutput {
	return o.ApplyT(func(v *EdgeRouterPolicy) NamedRoleArrayOutput { return v.IdentityRolesDisplay }).(NamedRoleArrayOutput)
}

func (o EdgeRouterPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *EdgeRouterPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o EdgeRouterPolicyOutput) Semantic() pulumi.StringOutput {
	return o.ApplyT(func(v *EdgeRouterPolicy) pulumi.StringOutput { return v.Semantic }).(pulumi.StringOutput)
}

func (o EdgeRouterPolicyOutput) Tags() pulumi.MapOutput {
	return o.ApplyT(func(v *EdgeRouterPolicy) pulumi.MapOutput { return v.Tags }).(pulumi.MapOutput)
}

func (o EdgeRouterPolicyOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *EdgeRouterPolicy) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

func (o EdgeRouterPolicyOutput) ZitiId() pulumi.StringOutput {
	return o.ApplyT(func(v *EdgeRouterPolicy) pulumi.StringOutput { return v.ZitiId }).(pulumi.StringOutput)
}

type EdgeRouterPolicyArrayOutput struct{ *pulumi.OutputState }

func (EdgeRouterPolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EdgeRouterPolicy)(nil)).Elem()
}

func (o EdgeRouterPolicyArrayOutput) ToEdgeRouterPolicyArrayOutput() EdgeRouterPolicyArrayOutput {
	return o
}

func (o EdgeRouterPolicyArrayOutput) ToEdgeRouterPolicyArrayOutputWithContext(ctx context.Context) EdgeRouterPolicyArrayOutput {
	return o
}

func (o EdgeRouterPolicyArrayOutput) Index(i pulumi.IntInput) EdgeRouterPolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *EdgeRouterPolicy {
		return vs[0].([]*EdgeRouterPolicy)[vs[1].(int)]
	}).(EdgeRouterPolicyOutput)
}

type EdgeRouterPolicyMapOutput struct{ *pulumi.OutputState }

func (EdgeRouterPolicyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EdgeRouterPolicy)(nil)).Elem()
}

func (o EdgeRouterPolicyMapOutput) ToEdgeRouterPolicyMapOutput() EdgeRouterPolicyMapOutput {
	return o
}

func (o EdgeRouterPolicyMapOutput) ToEdgeRouterPolicyMapOutputWithContext(ctx context.Context) EdgeRouterPolicyMapOutput {
	return o
}

func (o EdgeRouterPolicyMapOutput) MapIndex(k pulumi.StringInput) EdgeRouterPolicyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *EdgeRouterPolicy {
		return vs[0].(map[string]*EdgeRouterPolicy)[vs[1].(string)]
	}).(EdgeRouterPolicyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EdgeRouterPolicyInput)(nil)).Elem(), &EdgeRouterPolicy{})
	pulumi.RegisterInputType(reflect.TypeOf((*EdgeRouterPolicyArrayInput)(nil)).Elem(), EdgeRouterPolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*EdgeRouterPolicyMapInput)(nil)).Elem(), EdgeRouterPolicyMap{})
	pulumi.RegisterOutputType(EdgeRouterPolicyOutput{})
	pulumi.RegisterOutputType(EdgeRouterPolicyArrayOutput{})
	pulumi.RegisterOutputType(EdgeRouterPolicyMapOutput{})
}
