// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumiopenziti

import (
	"context"
	"reflect"

	"errors"
	"github.com/OSMIT-GmbH/pulumi-openziti/sdk/go/pulumi-openziti/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ServiceEdgeRouterPolicy struct {
	pulumi.CustomResourceState

	_assimilated           pulumi.BoolOutput        `pulumi:"_assimilated"`
	_links                 LinkMapOutput            `pulumi:"_links"`
	CreatedAt              pulumi.StringOutput      `pulumi:"createdAt"`
	EdgeRouterRoles        pulumi.StringArrayOutput `pulumi:"edgeRouterRoles"`
	EdgeRouterRolesDisplay NamedRoleArrayOutput     `pulumi:"edgeRouterRolesDisplay"`
	Name                   pulumi.StringOutput      `pulumi:"name"`
	Semantic               pulumi.StringOutput      `pulumi:"semantic"`
	ServiceRoles           pulumi.StringArrayOutput `pulumi:"serviceRoles"`
	ServiceRolesDisplay    NamedRoleArrayOutput     `pulumi:"serviceRolesDisplay"`
	Tags                   pulumi.MapOutput         `pulumi:"tags"`
	UpdatedAt              pulumi.StringOutput      `pulumi:"updatedAt"`
	ZitiId                 pulumi.StringOutput      `pulumi:"zitiId"`
}

// NewServiceEdgeRouterPolicy registers a new resource with the given unique name, arguments, and options.
func NewServiceEdgeRouterPolicy(ctx *pulumi.Context,
	name string, args *ServiceEdgeRouterPolicyArgs, opts ...pulumi.ResourceOption) (*ServiceEdgeRouterPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Semantic == nil {
		return nil, errors.New("invalid value for required argument 'Semantic'")
	}
	if args.ServiceRoles == nil {
		return nil, errors.New("invalid value for required argument 'ServiceRoles'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ServiceEdgeRouterPolicy
	err := ctx.RegisterResource("openziti:index:ServiceEdgeRouterPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServiceEdgeRouterPolicy gets an existing ServiceEdgeRouterPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServiceEdgeRouterPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServiceEdgeRouterPolicyState, opts ...pulumi.ResourceOption) (*ServiceEdgeRouterPolicy, error) {
	var resource ServiceEdgeRouterPolicy
	err := ctx.ReadResource("openziti:index:ServiceEdgeRouterPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ServiceEdgeRouterPolicy resources.
type serviceEdgeRouterPolicyState struct {
}

type ServiceEdgeRouterPolicyState struct {
}

func (ServiceEdgeRouterPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*serviceEdgeRouterPolicyState)(nil)).Elem()
}

type serviceEdgeRouterPolicyArgs struct {
	EdgeRouterRoles []string               `pulumi:"edgeRouterRoles"`
	Name            string                 `pulumi:"name"`
	Semantic        string                 `pulumi:"semantic"`
	ServiceRoles    []string               `pulumi:"serviceRoles"`
	Tags            map[string]interface{} `pulumi:"tags"`
}

// The set of arguments for constructing a ServiceEdgeRouterPolicy resource.
type ServiceEdgeRouterPolicyArgs struct {
	EdgeRouterRoles pulumi.StringArrayInput
	Name            pulumi.StringInput
	Semantic        pulumi.StringInput
	ServiceRoles    pulumi.StringArrayInput
	Tags            pulumi.MapInput
}

func (ServiceEdgeRouterPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serviceEdgeRouterPolicyArgs)(nil)).Elem()
}

type ServiceEdgeRouterPolicyInput interface {
	pulumi.Input

	ToServiceEdgeRouterPolicyOutput() ServiceEdgeRouterPolicyOutput
	ToServiceEdgeRouterPolicyOutputWithContext(ctx context.Context) ServiceEdgeRouterPolicyOutput
}

func (*ServiceEdgeRouterPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceEdgeRouterPolicy)(nil)).Elem()
}

func (i *ServiceEdgeRouterPolicy) ToServiceEdgeRouterPolicyOutput() ServiceEdgeRouterPolicyOutput {
	return i.ToServiceEdgeRouterPolicyOutputWithContext(context.Background())
}

func (i *ServiceEdgeRouterPolicy) ToServiceEdgeRouterPolicyOutputWithContext(ctx context.Context) ServiceEdgeRouterPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEdgeRouterPolicyOutput)
}

// ServiceEdgeRouterPolicyArrayInput is an input type that accepts ServiceEdgeRouterPolicyArray and ServiceEdgeRouterPolicyArrayOutput values.
// You can construct a concrete instance of `ServiceEdgeRouterPolicyArrayInput` via:
//
//	ServiceEdgeRouterPolicyArray{ ServiceEdgeRouterPolicyArgs{...} }
type ServiceEdgeRouterPolicyArrayInput interface {
	pulumi.Input

	ToServiceEdgeRouterPolicyArrayOutput() ServiceEdgeRouterPolicyArrayOutput
	ToServiceEdgeRouterPolicyArrayOutputWithContext(context.Context) ServiceEdgeRouterPolicyArrayOutput
}

type ServiceEdgeRouterPolicyArray []ServiceEdgeRouterPolicyInput

func (ServiceEdgeRouterPolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServiceEdgeRouterPolicy)(nil)).Elem()
}

func (i ServiceEdgeRouterPolicyArray) ToServiceEdgeRouterPolicyArrayOutput() ServiceEdgeRouterPolicyArrayOutput {
	return i.ToServiceEdgeRouterPolicyArrayOutputWithContext(context.Background())
}

func (i ServiceEdgeRouterPolicyArray) ToServiceEdgeRouterPolicyArrayOutputWithContext(ctx context.Context) ServiceEdgeRouterPolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEdgeRouterPolicyArrayOutput)
}

// ServiceEdgeRouterPolicyMapInput is an input type that accepts ServiceEdgeRouterPolicyMap and ServiceEdgeRouterPolicyMapOutput values.
// You can construct a concrete instance of `ServiceEdgeRouterPolicyMapInput` via:
//
//	ServiceEdgeRouterPolicyMap{ "key": ServiceEdgeRouterPolicyArgs{...} }
type ServiceEdgeRouterPolicyMapInput interface {
	pulumi.Input

	ToServiceEdgeRouterPolicyMapOutput() ServiceEdgeRouterPolicyMapOutput
	ToServiceEdgeRouterPolicyMapOutputWithContext(context.Context) ServiceEdgeRouterPolicyMapOutput
}

type ServiceEdgeRouterPolicyMap map[string]ServiceEdgeRouterPolicyInput

func (ServiceEdgeRouterPolicyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServiceEdgeRouterPolicy)(nil)).Elem()
}

func (i ServiceEdgeRouterPolicyMap) ToServiceEdgeRouterPolicyMapOutput() ServiceEdgeRouterPolicyMapOutput {
	return i.ToServiceEdgeRouterPolicyMapOutputWithContext(context.Background())
}

func (i ServiceEdgeRouterPolicyMap) ToServiceEdgeRouterPolicyMapOutputWithContext(ctx context.Context) ServiceEdgeRouterPolicyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEdgeRouterPolicyMapOutput)
}

type ServiceEdgeRouterPolicyOutput struct{ *pulumi.OutputState }

func (ServiceEdgeRouterPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceEdgeRouterPolicy)(nil)).Elem()
}

func (o ServiceEdgeRouterPolicyOutput) ToServiceEdgeRouterPolicyOutput() ServiceEdgeRouterPolicyOutput {
	return o
}

func (o ServiceEdgeRouterPolicyOutput) ToServiceEdgeRouterPolicyOutputWithContext(ctx context.Context) ServiceEdgeRouterPolicyOutput {
	return o
}

func (o ServiceEdgeRouterPolicyOutput) _assimilated() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServiceEdgeRouterPolicy) pulumi.BoolOutput { return v._assimilated }).(pulumi.BoolOutput)
}

func (o ServiceEdgeRouterPolicyOutput) _links() LinkMapOutput {
	return o.ApplyT(func(v *ServiceEdgeRouterPolicy) LinkMapOutput { return v._links }).(LinkMapOutput)
}

func (o ServiceEdgeRouterPolicyOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceEdgeRouterPolicy) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o ServiceEdgeRouterPolicyOutput) EdgeRouterRoles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ServiceEdgeRouterPolicy) pulumi.StringArrayOutput { return v.EdgeRouterRoles }).(pulumi.StringArrayOutput)
}

func (o ServiceEdgeRouterPolicyOutput) EdgeRouterRolesDisplay() NamedRoleArrayOutput {
	return o.ApplyT(func(v *ServiceEdgeRouterPolicy) NamedRoleArrayOutput { return v.EdgeRouterRolesDisplay }).(NamedRoleArrayOutput)
}

func (o ServiceEdgeRouterPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceEdgeRouterPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o ServiceEdgeRouterPolicyOutput) Semantic() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceEdgeRouterPolicy) pulumi.StringOutput { return v.Semantic }).(pulumi.StringOutput)
}

func (o ServiceEdgeRouterPolicyOutput) ServiceRoles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ServiceEdgeRouterPolicy) pulumi.StringArrayOutput { return v.ServiceRoles }).(pulumi.StringArrayOutput)
}

func (o ServiceEdgeRouterPolicyOutput) ServiceRolesDisplay() NamedRoleArrayOutput {
	return o.ApplyT(func(v *ServiceEdgeRouterPolicy) NamedRoleArrayOutput { return v.ServiceRolesDisplay }).(NamedRoleArrayOutput)
}

func (o ServiceEdgeRouterPolicyOutput) Tags() pulumi.MapOutput {
	return o.ApplyT(func(v *ServiceEdgeRouterPolicy) pulumi.MapOutput { return v.Tags }).(pulumi.MapOutput)
}

func (o ServiceEdgeRouterPolicyOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceEdgeRouterPolicy) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

func (o ServiceEdgeRouterPolicyOutput) ZitiId() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceEdgeRouterPolicy) pulumi.StringOutput { return v.ZitiId }).(pulumi.StringOutput)
}

type ServiceEdgeRouterPolicyArrayOutput struct{ *pulumi.OutputState }

func (ServiceEdgeRouterPolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServiceEdgeRouterPolicy)(nil)).Elem()
}

func (o ServiceEdgeRouterPolicyArrayOutput) ToServiceEdgeRouterPolicyArrayOutput() ServiceEdgeRouterPolicyArrayOutput {
	return o
}

func (o ServiceEdgeRouterPolicyArrayOutput) ToServiceEdgeRouterPolicyArrayOutputWithContext(ctx context.Context) ServiceEdgeRouterPolicyArrayOutput {
	return o
}

func (o ServiceEdgeRouterPolicyArrayOutput) Index(i pulumi.IntInput) ServiceEdgeRouterPolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ServiceEdgeRouterPolicy {
		return vs[0].([]*ServiceEdgeRouterPolicy)[vs[1].(int)]
	}).(ServiceEdgeRouterPolicyOutput)
}

type ServiceEdgeRouterPolicyMapOutput struct{ *pulumi.OutputState }

func (ServiceEdgeRouterPolicyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServiceEdgeRouterPolicy)(nil)).Elem()
}

func (o ServiceEdgeRouterPolicyMapOutput) ToServiceEdgeRouterPolicyMapOutput() ServiceEdgeRouterPolicyMapOutput {
	return o
}

func (o ServiceEdgeRouterPolicyMapOutput) ToServiceEdgeRouterPolicyMapOutputWithContext(ctx context.Context) ServiceEdgeRouterPolicyMapOutput {
	return o
}

func (o ServiceEdgeRouterPolicyMapOutput) MapIndex(k pulumi.StringInput) ServiceEdgeRouterPolicyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ServiceEdgeRouterPolicy {
		return vs[0].(map[string]*ServiceEdgeRouterPolicy)[vs[1].(string)]
	}).(ServiceEdgeRouterPolicyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceEdgeRouterPolicyInput)(nil)).Elem(), &ServiceEdgeRouterPolicy{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceEdgeRouterPolicyArrayInput)(nil)).Elem(), ServiceEdgeRouterPolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceEdgeRouterPolicyMapInput)(nil)).Elem(), ServiceEdgeRouterPolicyMap{})
	pulumi.RegisterOutputType(ServiceEdgeRouterPolicyOutput{})
	pulumi.RegisterOutputType(ServiceEdgeRouterPolicyArrayOutput{})
	pulumi.RegisterOutputType(ServiceEdgeRouterPolicyMapOutput{})
}
