// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openziti.Inputs
{

    public sealed class IdentityCreateEnrollmentArgs : global::Pulumi.ResourceArgs
    {
        [Input("ott")]
        public Input<bool>? Ott { get; set; }

        [Input("ottca")]
        public Input<string>? Ottca { get; set; }

        [Input("updb")]
        public Input<string>? Updb { get; set; }

        public IdentityCreateEnrollmentArgs()
        {
        }
        public static new IdentityCreateEnrollmentArgs Empty => new IdentityCreateEnrollmentArgs();
    }
}
