// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class EdgeRouterPolicy extends pulumi.CustomResource {
    /**
     * Get an existing EdgeRouterPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): EdgeRouterPolicy {
        return new EdgeRouterPolicy(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'openziti:index:EdgeRouterPolicy';

    /**
     * Returns true if the given object is an instance of EdgeRouterPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EdgeRouterPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EdgeRouterPolicy.__pulumiType;
    }

    public /*out*/ readonly _links!: pulumi.Output<{[key: string]: outputs.Link}>;
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    public readonly edgeRouterRoles!: pulumi.Output<string[]>;
    public /*out*/ readonly edgeRouterRolesDisplay!: pulumi.Output<outputs.NamedRole[]>;
    public /*out*/ readonly id!: pulumi.Output<string>;
    public readonly identityRoles!: pulumi.Output<string[]>;
    public /*out*/ readonly identityRolesDisplay!: pulumi.Output<outputs.NamedRole[]>;
    public readonly name!: pulumi.Output<string>;
    public readonly semantic!: pulumi.Output<string>;
    public readonly tags!: pulumi.Output<{[key: string]: any} | undefined>;
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;

    /**
     * Create a EdgeRouterPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EdgeRouterPolicyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.identityRoles === undefined) && !opts.urn) {
                throw new Error("Missing required property 'identityRoles'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if ((!args || args.semantic === undefined) && !opts.urn) {
                throw new Error("Missing required property 'semantic'");
            }
            resourceInputs["edgeRouterRoles"] = args ? args.edgeRouterRoles : undefined;
            resourceInputs["identityRoles"] = args ? args.identityRoles : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["semantic"] = args ? args.semantic : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["_links"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["edgeRouterRolesDisplay"] = undefined /*out*/;
            resourceInputs["id"] = undefined /*out*/;
            resourceInputs["identityRolesDisplay"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        } else {
            resourceInputs["_links"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["edgeRouterRoles"] = undefined /*out*/;
            resourceInputs["edgeRouterRolesDisplay"] = undefined /*out*/;
            resourceInputs["id"] = undefined /*out*/;
            resourceInputs["identityRoles"] = undefined /*out*/;
            resourceInputs["identityRolesDisplay"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["semantic"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EdgeRouterPolicy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a EdgeRouterPolicy resource.
 */
export interface EdgeRouterPolicyArgs {
    edgeRouterRoles?: pulumi.Input<pulumi.Input<string>[]>;
    identityRoles: pulumi.Input<pulumi.Input<string>[]>;
    name: pulumi.Input<string>;
    semantic: pulumi.Input<string>;
    tags?: pulumi.Input<{[key: string]: any}>;
}
