// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class EdgeRouter extends pulumi.CustomResource {
    /**
     * Get an existing EdgeRouter resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): EdgeRouter {
        return new EdgeRouter(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'openziti:index:EdgeRouter';

    /**
     * Returns true if the given object is an instance of EdgeRouter.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EdgeRouter {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EdgeRouter.__pulumiType;
    }

    declare public /*out*/ readonly _assimilated: pulumi.Output<boolean>;
    declare public /*out*/ readonly _links: pulumi.Output<{[key: string]: outputs.Link}>;
    declare public readonly appData: pulumi.Output<{[key: string]: any} | undefined>;
    declare public /*out*/ readonly certPem: pulumi.Output<string | undefined>;
    declare public readonly cost: pulumi.Output<number>;
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    declare public readonly disabled: pulumi.Output<boolean>;
    declare public /*out*/ readonly enrollmentCreatedAt: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly enrollmentExpiresAt: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly enrollmentJwt: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly enrollmentToken: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly fingerprint: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly hostname: pulumi.Output<string>;
    declare public /*out*/ readonly isOnline: pulumi.Output<boolean>;
    declare public readonly isTunnelerEnabled: pulumi.Output<boolean>;
    declare public /*out*/ readonly isVerified: pulumi.Output<boolean>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly noTraversal: pulumi.Output<boolean>;
    declare public readonly roleAttributes: pulumi.Output<string[]>;
    declare public /*out*/ readonly supportedProtocols: pulumi.Output<{[key: string]: string}>;
    declare public /*out*/ readonly syncStatus: pulumi.Output<string>;
    declare public readonly tags: pulumi.Output<{[key: string]: any} | undefined>;
    declare public /*out*/ readonly unverifiedCertPem: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly unverifiedFingerprint: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    declare public /*out*/ readonly zitiId: pulumi.Output<string>;

    /**
     * Create a EdgeRouter resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EdgeRouterArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["appData"] = args?.appData;
            resourceInputs["cost"] = args?.cost;
            resourceInputs["disabled"] = args?.disabled;
            resourceInputs["isTunnelerEnabled"] = args?.isTunnelerEnabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["noTraversal"] = args?.noTraversal;
            resourceInputs["roleAttributes"] = args?.roleAttributes;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["_assimilated"] = undefined /*out*/;
            resourceInputs["_links"] = undefined /*out*/;
            resourceInputs["certPem"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["enrollmentCreatedAt"] = undefined /*out*/;
            resourceInputs["enrollmentExpiresAt"] = undefined /*out*/;
            resourceInputs["enrollmentJwt"] = undefined /*out*/;
            resourceInputs["enrollmentToken"] = undefined /*out*/;
            resourceInputs["fingerprint"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["isOnline"] = undefined /*out*/;
            resourceInputs["isVerified"] = undefined /*out*/;
            resourceInputs["supportedProtocols"] = undefined /*out*/;
            resourceInputs["syncStatus"] = undefined /*out*/;
            resourceInputs["unverifiedCertPem"] = undefined /*out*/;
            resourceInputs["unverifiedFingerprint"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["zitiId"] = undefined /*out*/;
        } else {
            resourceInputs["_assimilated"] = undefined /*out*/;
            resourceInputs["_links"] = undefined /*out*/;
            resourceInputs["appData"] = undefined /*out*/;
            resourceInputs["certPem"] = undefined /*out*/;
            resourceInputs["cost"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["disabled"] = undefined /*out*/;
            resourceInputs["enrollmentCreatedAt"] = undefined /*out*/;
            resourceInputs["enrollmentExpiresAt"] = undefined /*out*/;
            resourceInputs["enrollmentJwt"] = undefined /*out*/;
            resourceInputs["enrollmentToken"] = undefined /*out*/;
            resourceInputs["fingerprint"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["isOnline"] = undefined /*out*/;
            resourceInputs["isTunnelerEnabled"] = undefined /*out*/;
            resourceInputs["isVerified"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["noTraversal"] = undefined /*out*/;
            resourceInputs["roleAttributes"] = undefined /*out*/;
            resourceInputs["supportedProtocols"] = undefined /*out*/;
            resourceInputs["syncStatus"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["unverifiedCertPem"] = undefined /*out*/;
            resourceInputs["unverifiedFingerprint"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["zitiId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["enrollmentJwt", "enrollmentToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(EdgeRouter.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a EdgeRouter resource.
 */
export interface EdgeRouterArgs {
    appData?: pulumi.Input<{[key: string]: any} | undefined>;
    cost?: pulumi.Input<number | undefined>;
    disabled?: pulumi.Input<boolean | undefined>;
    isTunnelerEnabled?: pulumi.Input<boolean | undefined>;
    name: pulumi.Input<string>;
    noTraversal?: pulumi.Input<boolean | undefined>;
    roleAttributes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    tags?: pulumi.Input<{[key: string]: any} | undefined>;
}
