// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Identity extends pulumi.CustomResource {
    /**
     * Get an existing Identity resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Identity {
        return new Identity(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'openziti:index:Identity';

    /**
     * Returns true if the given object is an instance of Identity.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Identity {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Identity.__pulumiType;
    }

    declare public /*out*/ readonly _assimilated: pulumi.Output<boolean>;
    declare public /*out*/ readonly _links: pulumi.Output<{[key: string]: outputs.Link}>;
    declare public readonly appData: pulumi.Output<{[key: string]: any} | undefined>;
    declare public /*out*/ readonly authPolicy: pulumi.Output<outputs.EntityRef>;
    declare public readonly authPolicyId: pulumi.Output<string>;
    declare public /*out*/ readonly authenticators: pulumi.Output<outputs.rest_model.IdentityAuthenticators>;
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    declare public readonly defaultHostingCost: pulumi.Output<number>;
    declare public readonly defaultHostingPrecedence: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly disabled: pulumi.Output<boolean>;
    declare public /*out*/ readonly disabledAt: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly disabledUntil: pulumi.Output<string | undefined>;
    declare public readonly enrollment: pulumi.Output<outputs.IdentityEnrollments>;
    declare public /*out*/ readonly envInfo: pulumi.Output<outputs.EnvInfo>;
    declare public readonly externalId: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly hasApiSession: pulumi.Output<boolean>;
    declare public /*out*/ readonly hasEdgeRouterConnection: pulumi.Output<boolean>;
    declare public readonly isAdmin: pulumi.Output<boolean>;
    declare public /*out*/ readonly isDefaultAdmin: pulumi.Output<boolean>;
    declare public /*out*/ readonly isMfaEnabled: pulumi.Output<boolean>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly roleAttributes: pulumi.Output<string[]>;
    declare public /*out*/ readonly sdkInfo: pulumi.Output<outputs.SdkInfo>;
    declare public readonly serviceHostingCosts: pulumi.Output<{[key: string]: number}>;
    declare public readonly serviceHostingPrecedences: pulumi.Output<{[key: string]: string}>;
    declare public readonly tags: pulumi.Output<{[key: string]: any} | undefined>;
    declare public readonly type: pulumi.Output<outputs.EntityRef>;
    declare public /*out*/ readonly typeId: pulumi.Output<string>;
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    declare public /*out*/ readonly zitiId: pulumi.Output<string>;

    /**
     * Create a Identity resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IdentityArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.isAdmin === undefined && !opts.urn) {
                throw new Error("Missing required property 'isAdmin'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["appData"] = args?.appData;
            resourceInputs["authPolicyId"] = args?.authPolicyId;
            resourceInputs["defaultHostingCost"] = args?.defaultHostingCost;
            resourceInputs["defaultHostingPrecedence"] = args?.defaultHostingPrecedence;
            resourceInputs["enrollment"] = args?.enrollment;
            resourceInputs["externalId"] = args?.externalId;
            resourceInputs["isAdmin"] = args?.isAdmin;
            resourceInputs["name"] = args?.name;
            resourceInputs["roleAttributes"] = args?.roleAttributes;
            resourceInputs["serviceHostingCosts"] = args?.serviceHostingCosts;
            resourceInputs["serviceHostingPrecedences"] = args?.serviceHostingPrecedences;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["type"] = args?.type;
            resourceInputs["_assimilated"] = undefined /*out*/;
            resourceInputs["_links"] = undefined /*out*/;
            resourceInputs["authPolicy"] = undefined /*out*/;
            resourceInputs["authenticators"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["disabled"] = undefined /*out*/;
            resourceInputs["disabledAt"] = undefined /*out*/;
            resourceInputs["disabledUntil"] = undefined /*out*/;
            resourceInputs["envInfo"] = undefined /*out*/;
            resourceInputs["hasApiSession"] = undefined /*out*/;
            resourceInputs["hasEdgeRouterConnection"] = undefined /*out*/;
            resourceInputs["isDefaultAdmin"] = undefined /*out*/;
            resourceInputs["isMfaEnabled"] = undefined /*out*/;
            resourceInputs["sdkInfo"] = undefined /*out*/;
            resourceInputs["typeId"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["zitiId"] = undefined /*out*/;
        } else {
            resourceInputs["_assimilated"] = undefined /*out*/;
            resourceInputs["_links"] = undefined /*out*/;
            resourceInputs["appData"] = undefined /*out*/;
            resourceInputs["authPolicy"] = undefined /*out*/;
            resourceInputs["authPolicyId"] = undefined /*out*/;
            resourceInputs["authenticators"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["defaultHostingCost"] = undefined /*out*/;
            resourceInputs["defaultHostingPrecedence"] = undefined /*out*/;
            resourceInputs["disabled"] = undefined /*out*/;
            resourceInputs["disabledAt"] = undefined /*out*/;
            resourceInputs["disabledUntil"] = undefined /*out*/;
            resourceInputs["enrollment"] = undefined /*out*/;
            resourceInputs["envInfo"] = undefined /*out*/;
            resourceInputs["externalId"] = undefined /*out*/;
            resourceInputs["hasApiSession"] = undefined /*out*/;
            resourceInputs["hasEdgeRouterConnection"] = undefined /*out*/;
            resourceInputs["isAdmin"] = undefined /*out*/;
            resourceInputs["isDefaultAdmin"] = undefined /*out*/;
            resourceInputs["isMfaEnabled"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["roleAttributes"] = undefined /*out*/;
            resourceInputs["sdkInfo"] = undefined /*out*/;
            resourceInputs["serviceHostingCosts"] = undefined /*out*/;
            resourceInputs["serviceHostingPrecedences"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["typeId"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["zitiId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["enrollment"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Identity.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Identity resource.
 */
export interface IdentityArgs {
    appData?: pulumi.Input<{[key: string]: any} | undefined>;
    authPolicyId?: pulumi.Input<string | undefined>;
    defaultHostingCost?: pulumi.Input<number | undefined>;
    defaultHostingPrecedence?: pulumi.Input<string | undefined>;
    enrollment?: pulumi.Input<inputs.IdentityCreateEnrollmentArgs | undefined>;
    externalId?: pulumi.Input<string | undefined>;
    isAdmin: pulumi.Input<boolean>;
    name: pulumi.Input<string>;
    roleAttributes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    serviceHostingCosts?: pulumi.Input<{[key: string]: pulumi.Input<number>} | undefined>;
    serviceHostingPrecedences?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    tags?: pulumi.Input<{[key: string]: any} | undefined>;
    type: pulumi.Input<string>;
}
