// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ServicePolicy extends pulumi.CustomResource {
    /**
     * Get an existing ServicePolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ServicePolicy {
        return new ServicePolicy(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'openziti:index:ServicePolicy';

    /**
     * Returns true if the given object is an instance of ServicePolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServicePolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServicePolicy.__pulumiType;
    }

    declare public /*out*/ readonly _assimilated: pulumi.Output<boolean>;
    declare public /*out*/ readonly _links: pulumi.Output<{[key: string]: outputs.Link}>;
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    declare public readonly identityRoles: pulumi.Output<string[]>;
    declare public /*out*/ readonly identityRolesDisplay: pulumi.Output<outputs.NamedRole[]>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly postureCheckRoles: pulumi.Output<string[]>;
    declare public /*out*/ readonly postureCheckRolesDisplay: pulumi.Output<outputs.NamedRole[]>;
    declare public readonly semantic: pulumi.Output<string>;
    declare public readonly serviceRoles: pulumi.Output<string[]>;
    declare public /*out*/ readonly serviceRolesDisplay: pulumi.Output<outputs.NamedRole[]>;
    declare public readonly tags: pulumi.Output<{[key: string]: any} | undefined>;
    declare public readonly type: pulumi.Output<string>;
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    declare public /*out*/ readonly zitiId: pulumi.Output<string>;

    /**
     * Create a ServicePolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServicePolicyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.identityRoles === undefined && !opts.urn) {
                throw new Error("Missing required property 'identityRoles'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.semantic === undefined && !opts.urn) {
                throw new Error("Missing required property 'semantic'");
            }
            if (args?.serviceRoles === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceRoles'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["identityRoles"] = args?.identityRoles;
            resourceInputs["name"] = args?.name;
            resourceInputs["postureCheckRoles"] = args?.postureCheckRoles;
            resourceInputs["semantic"] = args?.semantic;
            resourceInputs["serviceRoles"] = args?.serviceRoles;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["type"] = args?.type;
            resourceInputs["_assimilated"] = undefined /*out*/;
            resourceInputs["_links"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["identityRolesDisplay"] = undefined /*out*/;
            resourceInputs["postureCheckRolesDisplay"] = undefined /*out*/;
            resourceInputs["serviceRolesDisplay"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["zitiId"] = undefined /*out*/;
        } else {
            resourceInputs["_assimilated"] = undefined /*out*/;
            resourceInputs["_links"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["identityRoles"] = undefined /*out*/;
            resourceInputs["identityRolesDisplay"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["postureCheckRoles"] = undefined /*out*/;
            resourceInputs["postureCheckRolesDisplay"] = undefined /*out*/;
            resourceInputs["semantic"] = undefined /*out*/;
            resourceInputs["serviceRoles"] = undefined /*out*/;
            resourceInputs["serviceRolesDisplay"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["zitiId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServicePolicy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ServicePolicy resource.
 */
export interface ServicePolicyArgs {
    identityRoles: pulumi.Input<pulumi.Input<string>[]>;
    name: pulumi.Input<string>;
    postureCheckRoles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    semantic: pulumi.Input<string>;
    serviceRoles: pulumi.Input<pulumi.Input<string>[]>;
    tags?: pulumi.Input<{[key: string]: any} | undefined>;
    type: pulumi.Input<string>;
}
